In [117]:
import pandas as pd

In [118]:
a = pd.Series([100, 150, 200, 175, 250])

print(a)

0    100
1    150
2    200
3    175
4    250
dtype: int64

In [119]:
sales = pd.Series(
    [100, 150, 200],
    index=["Monday", "Tuesday", "Wednesday"]
)

print(sales)

Monday       100
Tuesday      150
Wednesday    200
dtype: int64

In [120]:
print(sales["Tuesday"])

150

In [121]:
print(sales)
print()
print("Tuesday sales:", sales["Tuesday"])
print("Total sales:", sales.sum())
print("Average sales:", sales.mean())
print("Maximum sales:", sales.max())

Monday       100
Tuesday      150
Wednesday    200
dtype: int64

Tuesday sales: 150
Total sales: 450
Average sales: 150.0
Maximum sales: 200

In [122]:
data = {
    "product": ["Pen", "Book", "Bag"],
    "price": [10, 50, 500],
    "quantity": [20, 10, 5]
}

df = pd.DataFrame(data)

print(df)

  product  price  quantity
0     Pen     10        20
1    Book     50        10
2     Bag    500         5

In [123]:
data = {
    "Name" : ["Yash", "Dhruv" , "Himalay" , "Nirbhay"],
    "Age" : [18 , 21 , 19 , 17 ],
    "Salary" : [20000 , 30000 , 40000 , 50000]
}
df = pd.DataFrame(data)

print(df)

      Name  Age  Salary
0     Yash   18   20000
1    Dhruv   21   30000
2  Himalay   19   40000
3  Nirbhay   17   50000

In [124]:
df["Salary"]

0    20000
1    30000
2    40000
3    50000
Name: Salary, dtype: int64

In [125]:
df["Salary"]>40000

0    False
1    False
2    False
3     True
Name: Salary, dtype: bool

In [126]:
a = df[df["Age"]>20]
print(a[["Name","Age","Salary"]])

    Name  Age  Salary
1  Dhruv   21   30000

In [127]:
a = df[(df["Age"]>18) & (df["Salary"]>10000)]
print(a[["Name","Age","Salary"]])

      Name  Age  Salary
1    Dhruv   21   30000
2  Himalay   19   40000

In [128]:
df.to_csv("output.csv")

In [129]:
df = pd.read_csv("emp.csv")
df

  employee department   salary
0     Amit         IT  40000.0
1      Raj         HR  35000.0
2     Neha         IT  50000.0
3    Kiran      Sales  30000.0
4     Raju        NaN      NaN
5     Kaju         HR      NaN

In [130]:
df.head(1)

  employee department   salary
0     Amit         IT  40000.0

In [131]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   employee    6 non-null      str
 1   department  5 non-null      str
 2   salary      4 non-null      float64
dtypes: float64(1), str(2)
memory usage: 314.0 bytes

In [132]:
df.shape

(6, 3)

In [133]:
df.isnull().sum(
    
)

employee      0
department    1
salary        2
dtype: int64

In [134]:
df.tail(1)

  employee department  salary
5     Kaju         HR     NaN

In [135]:
df.describe()

             salary
count      4.000000
mean   38750.000000
std     8539.125638
min    30000.000000
25%    33750.000000
50%    37500.000000
75%    42500.000000
max    50000.000000

In [136]:
print(df.columns)

Index(['employee', 'department', 'salary'], dtype='str')

In [137]:
print(df.dtypes)

employee          str
department        str
salary        float64
dtype: object

In [138]:
print(df.loc[0])

employee         Amit
department         IT
salary        40000.0
Name: 0, dtype: object

In [139]:
print(df.loc[[0, 2]])

  employee department   salary
0     Amit         IT  40000.0
2     Neha         IT  50000.0

In [140]:
df

  employee department   salary
0     Amit         IT  40000.0
1      Raj         HR  35000.0
2     Neha         IT  50000.0
3    Kiran      Sales  30000.0
4     Raju        NaN      NaN
5     Kaju         HR      NaN

In [141]:
print(df.iloc[0:2])

  employee department   salary
0     Amit         IT  40000.0
1      Raj         HR  35000.0

In [142]:
df.iloc[0]

employee         Amit
department         IT
salary        40000.0
Name: 0, dtype: object

In [143]:
print(df[df["department"]=="IT"])

  employee department   salary
0     Amit         IT  40000.0
2     Neha         IT  50000.0

In [144]:
print(df[(df["department"]=="IT") & (df["salary"]>40000)] )

  employee department   salary
2     Neha         IT  50000.0

In [145]:
print(df[(df["department"]=="IT") | (df["salary"]>40000)] )

  employee department   salary
0     Amit         IT  40000.0
2     Neha         IT  50000.0

In [146]:
df.isna()

   employee  department  salary
0     False       False   False
1     False       False   False
2     False       False   False
3     False       False   False
4     False        True    True
5     False       False    True

In [147]:
df.isnull

<bound method DataFrame.isnull of   employee department   salary
0     Amit         IT  40000.0
1      Raj         HR  35000.0
2     Neha         IT  50000.0
3    Kiran      Sales  30000.0
4     Raju        NaN      NaN
5     Kaju         HR      NaN>

In [148]:
df.isnull().sum()

employee      0
department    1
salary        2
dtype: int64

In [149]:
df_clean = df.dropna()
df_clean

  employee department   salary
0     Amit         IT  40000.0
1      Raj         HR  35000.0
2     Neha         IT  50000.0
3    Kiran      Sales  30000.0

In [150]:
df["salary"] = df["salary"].fillna(df["salary"].mean())
df

  employee department   salary
0     Amit         IT  40000.0
1      Raj         HR  35000.0
2     Neha         IT  50000.0
3    Kiran      Sales  30000.0
4     Raju        NaN  38750.0
5     Kaju         HR  38750.0

In [151]:
df["department"] = df["department"].fillna(df["department"].mode()[0])
df

  employee department   salary
0     Amit         IT  40000.0
1      Raj         HR  35000.0
2     Neha         IT  50000.0
3    Kiran      Sales  30000.0
4     Raju         HR  38750.0
5     Kaju         HR  38750.0

In [152]:
df["salary"].mode()

0    38750.0
Name: salary, dtype: float64

In [153]:
df["department"].mode()

0    HR
Name: department, dtype: str

In [154]:
df.sort_values("salary")

  employee department   salary
3    Kiran      Sales  30000.0
1      Raj         HR  35000.0
5     Kaju         HR  38750.0
4     Raju         HR  38750.0
0     Amit         IT  40000.0
2     Neha         IT  50000.0

In [155]:
df.sort_values("salary", ascending=False)

  employee department   salary
2     Neha         IT  50000.0
0     Amit         IT  40000.0
5     Kaju         HR  38750.0
4     Raju         HR  38750.0
1      Raj         HR  35000.0
3    Kiran      Sales  30000.0

In [156]:
df.sort_values(
    ["department", "salary"],
    ascending=[True, False]
)

  employee department   salary
4     Raju         HR  38750.0
5     Kaju         HR  38750.0
1      Raj         HR  35000.0
2     Neha         IT  50000.0
0     Amit         IT  40000.0
3    Kiran      Sales  30000.0

In [157]:
df.groupby("department")["salary"].sum()

department
HR       112500.0
IT        90000.0
Sales     30000.0
Name: salary, dtype: float64

In [158]:
df.groupby("department")["salary"].agg(
    ["sum", "mean", "max", "min"]
)

                 sum     mean      max      min
department
HR          112500.0  37500.0  38750.0  35000.0
IT           90000.0  45000.0  50000.0  40000.0
Sales        30000.0  30000.0  30000.0  30000.0

In [159]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3],
    "employee": ["Amit", "Neha", "Raj"],
    "dept_id": ["D01", "D02", "D01"],
    "salary": [40000, 50000, 35000]
})

departments = pd.DataFrame({
    "dept_id": ["D01", "D02"],
    "department": ["IT", "HR"]
})

In [160]:
result = pd.merge(
    employees,
    departments,
    on="dept_id",
    how="left"
)

print(result)

   employee_id employee dept_id  salary department
0            1     Amit     D01   40000         IT
1            2     Neha     D02   50000         HR
2            3      Raj     D01   35000         IT