# Data Validation

In [36]:
import logging

logging.basicConfig(
    filename="validation.log",
    level=logging.ERROR,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger(__name__)

In [2]:
import pandas as pd
import pandera.pandas as pa
from pandera import Column, Check 

df = pd.read_csv("employees.csv")

df.head()

,employee_id,employee_name,email,age,department,salary,joining_date,status
0,1001,Rahul Shah,rahul.shah@gmail.com,25.0,IT,45000,2023-01-15,Active
1,1002,Priya Patel,priya.patel@gmail.com,28.0,HR,52000,2022-03-20,Active
2,1003,Amit Mehta,amit.mehta@gmail.com,32.0,Finance,68000,2021-07-10,Active
3,1004,Neha Desai,neha.desai@gmail.com,24.0,Marketing,42000,2024-02-12,Active
4,1005,Rohan Shah,rohan.shah@gmail.com,29.0,IT,55000,2022-11-01,Inactive

In [3]:
df.shape

(50, 8)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    50 non-null     int64
 1   employee_name  50 non-null     str
 2   email          49 non-null     str
 3   age            49 non-null     float64
 4   department     50 non-null     str
 5   salary         50 non-null     int64
 6   joining_date   50 non-null     str
 7   status         50 non-null     str
dtypes: float64(1), int64(2), str(5)
memory usage: 5.8 KB

In [5]:
df.isnull

<bound method DataFrame.isnull of     employee_id   employee_name                     email   age department  \
0          1001      Rahul Shah      rahul.shah@gmail.com  25.0         IT
1          1002     Priya Patel     priya.patel@gmail.com  28.0         HR
2          1003      Amit Mehta      amit.mehta@gmail.com  32.0    Finance
3          1004      Neha Desai      neha.desai@gmail.com  24.0  Marketing
4          1005      Rohan Shah      rohan.shah@gmail.com  29.0         IT
5          1006     Kajal Patel     kajal.patel@gmail.com  31.0         HR
6          1007       Jay Mehta       jay.mehta@gmail.com  27.0    Finance
7          1008      Pooja Shah      pooja.shah@gmail.com  26.0  Marketing
8          1009       Dev Patel       dev.patel@gmail.com  35.0         IT
9          1010    Anjali Desai    anjali.desai@gmail.com  30.0         HR
10         1011      Vivek Shah      vivek.shah@gmail.com  22.0         IT
11         1012      Riya Patel      riya.patel@gmail.com  27.0    Finance
12         1013    Manish Mehta    manish.mehta@gmail.com  33.0  Marketing
13         1014      Hetal Shah      hetal.shah@gmail.com  29.0         HR
14         1015     Akash Patel     akash.patel@gmail.com  26.0         IT
15         1016    Simran Mehta    simran.mehta@gmail.com  34.0    Finance
16         1017      Parth Shah      parth.shah@gmail.com  23.0  Marketing
17         1018     Nisha Patel     nisha.patel@gmail.com  38.0         HR
18         1019     Kunal Mehta     kunal.mehta@gmail.com  41.0         IT
19         1020       Diya Shah       diya.shah@gmail.com  25.0    Finance
20         1021     Arjun Patel     arjun.patel@gmail.com  67.0         IT
21         1022      Meera Shah      meera.shah@gmail.com  28.0         HR
22         1023     Nirav Patel         nirav.patel@gmail  30.0    Finance
23         1024    Krisha Mehta    krisha.mehta@gmail.com  24.0  Marketing
24         1025      Dhruv Shah      dhruv.shah@gmail.com  36.0         IT
25         1026    Ankita Patel                       NaN  27.0         HR
26         1027     Harsh Mehta     harsh.mehta@gmail.com  31.0    Finance
27         1028       Isha Shah       isha.shah@gmail.com   NaN  Marketing
28         1029      Meet Patel      meet.patel@gmail.com  26.0         IT
29         1030     Komal Desai     komal.desai@gmail.com  29.0         HR
30         1031     Devang Shah     devang.shah@gmail.com  37.0    Finance
31         1032     Palak Patel     palak.patel@gmail.com  25.0  Marketing
32         1033    Chirag Mehta    chirag.mehta@gmail.com  45.0         IT
33         1034      Reema Shah      reema.shah@gmail.com  32.0         HR
34         1035     Varun Patel     varun.patel@gmail.com  28.0    Finance
35         1036     Krupa Mehta     krupa.mehta@gmail.com  23.0  Marketing
36         1037     Sameer Shah     sameer.shah@gmail.com  39.0         IT
37         1038     Payal Patel     payal.patel@gmail.com  30.0         HR
38         1039     Tejas Mehta     tejas.mehta@gmail.com  34.0    Finance
39         1040     Shreya Shah     shreya.shah@gmail.com  27.0  Marketing
40         1041  Abhishek Patel  abhishek.patel@gmail.com  29.0         IT
41         1042     Divya Mehta     divya.mehta@gmail.com  26.0         HR
42         1043     Mayank Shah     mayank.shah@gmail.com  33.0    Finance
43         1044    Sonali Patel    sonali.patel@gmail.com  31.0  Marketing
44         1045       Raj Mehta       raj.mehta@gmail.com  40.0         IT
45         1046        Anu Shah        anu.shah@gmail.com  28.0         HR
46         1047       Raj Mehta       raj.mehta@gmail.com  40.0         IT
47         1048      Yash Patel      yash.patel@gmail.com  30.0    Finance
48         1049      Mehul Shah      mehul.shah@gmail.com  17.0  Marketing
49         1050     Krish Patel     krish.patel@gmail.com  27.0         IT

    salary  joining_date    status
0    45000    2023-01-15    Active
1    52000    2022-03-20    Active
2    68000    2021-07-10    Active
3    42000    2024-02-12    Active
4    55000    2022-11-01  Inactive
5    48000    2020-08-19    Active
6    61000    2023-05-22    Active
7    47000    2023-09-15    Active
8    75000    2019-04-10    Active
9    58000    2021-12-01  Inactive
10   38000    2024-06-15    Active
11   62000    2022-01-18    Active
12   59000    2020-03-25    Active
13   51000    2023-10-10    Active
14  -45000    2022-05-12    Active
15   72000    2021-06-30    Active
16   40000    2024-01-05    Active
17   65000    2018-09-20  Inactive
18   85000    2017-02-14    Active
19   54000    2023-03-11    Active
20   90000    2016-05-18    Active
21   50000    2022-10-01    Active
22   63000    2021-11-12    Active
23   41000    2024-04-20    Active
24   78000    2019-08-15    Active
25   49000    2023-07-19    Active
26   67000    2020-12-10    Active
27   46000    2023-02-25    Active
28   53000    2022-09-01    Active
29   56000    2021-04-16  Inactive
30   71000    2019-10-20    Active
31   43000    2024-03-12    Active
32   95000    2015-07-01    Active
33   60000    2020-01-15    Active
34   64000    2022-06-18    Active
35   39000    2024-05-10    Active
36   82000    2018-03-22    Active
37   57000    2021-09-14    Active
38   69000    2020-07-08    Active
39   45000    2023-11-20    Active
40   58000    2022-02-05    Active
41   51000    2023-06-12    Active
42   73000    2019-12-01    Active
43   48000    2021-05-15    Active
44   88000    2017-11-10    Active
45   52000    2022-08-20    Active
46   88000    2017-11-10    Active
47   66000    2021-03-18    Active
48   37000    2024-07-01    Active
49   59000  invalid-date   Working  >

In [6]:
df.isnull().sum()

employee_id      0
employee_name    0
email            1
age              1
department       0
salary           0
joining_date     0
status           0
dtype: int64

In [7]:
df.describe()

       employee_id        age        salary
count     50.00000  49.000000     50.000000
mean    1025.50000  30.693878  57400.000000
std       14.57738   7.657252  20870.836992
min     1001.00000  17.000000 -45000.000000
25%     1013.25000  26.000000  48000.000000
50%     1025.50000  29.000000  57500.000000
75%     1037.75000  33.000000  67750.000000
max     1050.00000  67.000000  95000.000000

In [8]:
df.columns

Index(['employee_id', 'employee_name', 'email', 'age', 'department', 'salary',
       'joining_date', 'status'],
      dtype='str')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
print(df["employee_id"].duplicated().sum())
df.info()

0
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    50 non-null     int64
 1   employee_name  50 non-null     str
 2   email          49 non-null     str
 3   age            49 non-null     float64
 4   department     50 non-null     str
 5   salary         50 non-null     int64
 6   joining_date   50 non-null     str
 7   status         50 non-null     str
dtypes: float64(1), int64(2), str(5)
memory usage: 5.8 KB

In [14]:
schema = pa.DataFrameSchema({
    "employee_id": Column(
        int,
        Check.greater_than(0),
        nullable=False,
        unique=True
    ),

    "employee_name": Column(
        str,
        nullable=False
    ),

    "email": Column(
        str,
        nullable=False,
        checks=Check.str_matches(
            r"^[\w\.-]+@[\w\.-]+\.\w+$"
        )
    ),

    "age": Column(
        int,
        Check.in_range(18, 65),
        nullable=False
    ),

    "department": Column(
        str,
        Check.isin(["IT", "HR", "Finance", "Marketing"]),
        nullable=False
    ),

    "salary": Column(
        int,
        Check.greater_than(0),
        nullable=False
    ),

    "joining_date": Column(
        str,
        nullable=False,
        checks=Check.str_matches(
            r"^\d{4}-\d{2}-\d{2}$"
        )
    ),

    "status": Column(
        str,
        Check.isin(["Active", "Inactive"]),
        nullable=False
    )
})
df

,employee_id,employee_name,email,age,department,salary,joining_date,status
0,1001,Rahul Shah,rahul.shah@gmail.com,25.0,IT,45000,2023-01-15,Active
1,1002,Priya Patel,priya.patel@gmail.com,28.0,HR,52000,2022-03-20,Active
2,1003,Amit Mehta,amit.mehta@gmail.com,32.0,Finance,68000,2021-07-10,Active
3,1004,Neha Desai,neha.desai@gmail.com,24.0,Marketing,42000,2024-02-12,Active
4,1005,Rohan Shah,rohan.shah@gmail.com,29.0,IT,55000,2022-11-01,Inactive
5,1006,Kajal Patel,kajal.patel@gmail.com,31.0,HR,48000,2020-08-19,Active
6,1007,Jay Mehta,jay.mehta@gmail.com,27.0,Finance,61000,2023-05-22,Active
7,1008,Pooja Shah,pooja.shah@gmail.com,26.0,Marketing,47000,2023-09-15,Active
8,1009,Dev Patel,dev.patel@gmail.com,35.0,IT,75000,2019-04-10,Active
9,1010,Anjali Desai,anjali.desai@gmail.com,30.0,HR,58000,2021-12-01,Inactive
10,1011,Vivek Shah,vivek.shah@gmail.com,22.0,IT,38000,2024-06-15,Active
11,1012,Riya Patel,riya.patel@gmail.com,27.0,Finance,62000,2022-01-18,Active
12,1013,Manish Mehta,manish.mehta@gmail.com,33.0,Marketing,59000,2020-03-25,Active
13,1014,Hetal Shah,hetal.shah@gmail.com,29.0,HR,51000,2023-10-10,Active
14,1015,Akash Patel,akash.patel@gmail.com,26.0,IT,-45000,2022-05-12,Active
15,1016,Simran Mehta,simran.mehta@gmail.com,34.0,Finance,72000,2021-06-30,Active
16,1017,Parth Shah,parth.shah@gmail.com,23.0,Marketing,40000,2024-01-05,Active
17,1018,Nisha Patel,nisha.patel@gmail.com,38.0,HR,65000,2018-09-20,Inactive
18,1019,Kunal Mehta,kunal.mehta@gmail.com,41.0,IT,85000,2017-02-14,Active
19,1020,Diya Shah,diya.shah@gmail.com,25.0,Finance,54000,2023-03-11,Active
20,1021,Arjun Patel,arjun.patel@gmail.com,67.0,IT,90000,2016-05-18,Active
21,1022,Meera Shah,meera.shah@gmail.com,28.0,HR,50000,2022-10-01,Active
22,1023,Nirav Patel,nirav.patel@gmail,30.0,Finance,63000,2021-11-12,Active
23,1024,Krisha Mehta,krisha.mehta@gmail.com,24.0,Marketing,41000,2024-04-20,Active
24,1025,Dhruv Shah,dhruv.shah@gmail.com,36.0,IT,78000,2019-08-15,Active
25,1026,Ankita Patel,NaN,27.0,HR,49000,2023-07-19,Active
26,1027,Harsh Mehta,harsh.mehta@gmail.com,31.0,Finance,67000,2020-12-10,Active
27,1028,Isha Shah,isha.shah@gmail.com,NaN,Marketing,46000,2023-02-25,Active
28,1029,Meet Patel,meet.patel@gmail.com,26.0,IT,53000,2022-09-01,Active
29,1030,Komal Desai,komal.desai@gmail.com,29.0,HR,56000,2021-04-16,Inactive
30,1031,Devang Shah,devang.shah@gmail.com,37.0,Finance,71000,2019-10-20,Active
31,1032,Palak Patel,palak.patel@gmail.com,25.0,Marketing,43000,2024-03-12,Active
32,1033,Chirag Mehta,chirag.mehta@gmail.com,45.0,IT,95000,2015-07-01,Active
33,1034,Reema Shah,reema.shah@gmail.com,32.0,HR,60000,2020-01-15,Active
34,1035,Varun Patel,varun.patel@gmail.com,28.0,Finance,64000,2022-06-18,Active
35,1036,Krupa Mehta,krupa.mehta@gmail.com,23.0,Marketing,39000,2024-05-10,Active
36,1037,Sameer Shah,sameer.shah@gmail.com,39.0,IT,82000,2018-03-22,Active
37,1038,Payal Patel,payal.patel@gmail.com,30.0,HR,57000,2021-09-14,Active
38,1039,Tejas Mehta,tejas.mehta@gmail.com,34.0,Finance,69000,2020-07-08,Active
39,1040,Shreya Shah,shreya.shah@gmail.com,27.0,Marketing,45000,2023-11-20,Active
40,1041,Abhishek Patel,abhishek.patel@gmail.com,29.0,IT,58000,2022-02-05,Active
41,1042,Divya Mehta,divya.mehta@gmail.com,26.0,HR,51000,2023-06-12,Active
42,1043,Mayank Shah,mayank.shah@gmail.com,33.0,Finance,73000,2019-12-01,Active
43,1044,Sonali Patel,sonali.patel@gmail.com,31.0,Marketing,48000,2021-05-15,Active
44,1045,Raj Mehta,raj.mehta@gmail.com,40.0,IT,88000,2017-11-10,Active
45,1046,Anu Shah,anu.shah@gmail.com,28.0,HR,52000,2022-08-20,Active
46,1047,Raj Mehta,raj.mehta@gmail.com,40.0,IT,88000,2017-11-10,Active
47,1048,Yash Patel,yash.patel@gmail.com,30.0,Finance,66000,2021-03-18,Active
48,1049,Mehul Shah,mehul.shah@gmail.com,17.0,Marketing,37000,2024-07-01,Active
49,1050,Krish Patel,krish.patel@gmail.com,27.0,IT,59000,invalid-date,Working

In [12]:
validated_df = schema.validate(df)

SchemaError: non-nullable series 'email' contains null values:
25    NaN
Name: email, dtype: str

In [13]:
try:
    validated_df = schema.validate(df)
    print("Validation Passed")

except pa.errors.SchemaError as e:
    print("Validation Failed")
    print(e)

Validation Failed
non-nullable series 'email' contains null values:
25    NaN
Name: email, dtype: str

In [15]:
schema.validate(df)

SchemaError: non-nullable series 'email' contains null values:
25    NaN
Name: email, dtype: str

In [16]:
try:
    validated_df = schema.validate(df, lazy=True)
    print("Validation Passed")

except pa.errors.SchemaErrors as e:
    print("Validation Failed")
    print(e.failure_cases)

Validation Failed
  schema_context        column                                    check  \
0         Column         email                             not_nullable
1         Column         email  str_matches('^[\w\.-]+@[\w\.-]+\.\w+$')
2         Column           age                             not_nullable
3         Column           age                           dtype('int64')
4         Column           age                         in_range(18, 65)
5         Column           age                         in_range(18, 65)
6         Column        salary                          greater_than(0)
7         Column  joining_date       str_matches('^\d{4}-\d{2}-\d{2}$')
8         Column        status             isin(['Active', 'Inactive'])

  check_number       failure_case  index
0         None                NaN     25
1            0  nirav.patel@gmail     22
2         None                NaN     27
3         None                NaN     27
4            0               67.0     20
5            0               17.0     48
6            0             -45000     14
7            0       invalid-date     49
8            0            Working     49

In [17]:
try:
    validated_df = schema.validate(df, lazy=True)
    print("Validation Passed")

except pa.errors.SchemaErrors as e:
    errors = e.failure_cases

    print(errors)

  schema_context        column                                    check  \
0         Column         email                             not_nullable
1         Column         email  str_matches('^[\w\.-]+@[\w\.-]+\.\w+$')
2         Column           age                             not_nullable
3         Column           age                           dtype('int64')
4         Column           age                         in_range(18, 65)
5         Column           age                         in_range(18, 65)
6         Column        salary                          greater_than(0)
7         Column  joining_date       str_matches('^\d{4}-\d{2}-\d{2}$')
8         Column        status             isin(['Active', 'Inactive'])

  check_number       failure_case  index
0         None                NaN     25
1            0  nirav.patel@gmail     22
2         None                NaN     27
3         None                NaN     27
4            0               67.0     20
5            0               17.0     48
6            0             -45000     14
7            0       invalid-date     49
8            0            Working     49

In [18]:
print("Total Validation Errors:", len(errors))

Total Validation Errors: 9

In [19]:
print(errors.columns)

Index(['schema_context', 'column', 'check', 'check_number', 'failure_case',
       'index'],
      dtype='str')

In [20]:
print(
    errors[
        ["column", "check", "failure_case", "index"]
    ]
)

         column                                    check       failure_case  \
0         email                             not_nullable                NaN
1         email  str_matches('^[\w\.-]+@[\w\.-]+\.\w+$')  nirav.patel@gmail
2           age                             not_nullable                NaN
3           age                           dtype('int64')                NaN
4           age                         in_range(18, 65)               67.0
5           age                         in_range(18, 65)               17.0
6        salary                          greater_than(0)             -45000
7  joining_date       str_matches('^\d{4}-\d{2}-\d{2}$')       invalid-date
8        status             isin(['Active', 'Inactive'])            Working

   index
0     25
1     22
2     27
3     27
4     20
5     48
6     14
7     49
8     49

In [21]:
invalid_indexes = errors["index"].dropna().unique()

invalid_rows = df.loc[invalid_indexes]

print(invalid_rows)

    employee_id employee_name                  email   age department  salary  \
25         1026  Ankita Patel                    NaN  27.0         HR   49000
22         1023   Nirav Patel      nirav.patel@gmail  30.0    Finance   63000
27         1028     Isha Shah    isha.shah@gmail.com   NaN  Marketing   46000
20         1021   Arjun Patel  arjun.patel@gmail.com  67.0         IT   90000
48         1049    Mehul Shah   mehul.shah@gmail.com  17.0  Marketing   37000
14         1015   Akash Patel  akash.patel@gmail.com  26.0         IT  -45000
49         1050   Krish Patel  krish.patel@gmail.com  27.0         IT   59000

    joining_date   status
25    2023-07-19   Active
22    2021-11-12   Active
27    2023-02-25   Active
20    2016-05-18   Active
48    2024-07-01   Active
14    2022-05-12   Active
49  invalid-date  Working

In [22]:
valid_rows = df.drop(index=invalid_indexes)

print(valid_rows)

    employee_id   employee_name                     email   age department  \
0          1001      Rahul Shah      rahul.shah@gmail.com  25.0         IT
1          1002     Priya Patel     priya.patel@gmail.com  28.0         HR
2          1003      Amit Mehta      amit.mehta@gmail.com  32.0    Finance
3          1004      Neha Desai      neha.desai@gmail.com  24.0  Marketing
4          1005      Rohan Shah      rohan.shah@gmail.com  29.0         IT
5          1006     Kajal Patel     kajal.patel@gmail.com  31.0         HR
6          1007       Jay Mehta       jay.mehta@gmail.com  27.0    Finance
7          1008      Pooja Shah      pooja.shah@gmail.com  26.0  Marketing
8          1009       Dev Patel       dev.patel@gmail.com  35.0         IT
9          1010    Anjali Desai    anjali.desai@gmail.com  30.0         HR
10         1011      Vivek Shah      vivek.shah@gmail.com  22.0         IT
11         1012      Riya Patel      riya.patel@gmail.com  27.0    Finance
12         1013    Manish Mehta    manish.mehta@gmail.com  33.0  Marketing
13         1014      Hetal Shah      hetal.shah@gmail.com  29.0         HR
15         1016    Simran Mehta    simran.mehta@gmail.com  34.0    Finance
16         1017      Parth Shah      parth.shah@gmail.com  23.0  Marketing
17         1018     Nisha Patel     nisha.patel@gmail.com  38.0         HR
18         1019     Kunal Mehta     kunal.mehta@gmail.com  41.0         IT
19         1020       Diya Shah       diya.shah@gmail.com  25.0    Finance
21         1022      Meera Shah      meera.shah@gmail.com  28.0         HR
23         1024    Krisha Mehta    krisha.mehta@gmail.com  24.0  Marketing
24         1025      Dhruv Shah      dhruv.shah@gmail.com  36.0         IT
26         1027     Harsh Mehta     harsh.mehta@gmail.com  31.0    Finance
28         1029      Meet Patel      meet.patel@gmail.com  26.0         IT
29         1030     Komal Desai     komal.desai@gmail.com  29.0         HR
30         1031     Devang Shah     devang.shah@gmail.com  37.0    Finance
31         1032     Palak Patel     palak.patel@gmail.com  25.0  Marketing
32         1033    Chirag Mehta    chirag.mehta@gmail.com  45.0         IT
33         1034      Reema Shah      reema.shah@gmail.com  32.0         HR
34         1035     Varun Patel     varun.patel@gmail.com  28.0    Finance
35         1036     Krupa Mehta     krupa.mehta@gmail.com  23.0  Marketing
36         1037     Sameer Shah     sameer.shah@gmail.com  39.0         IT
37         1038     Payal Patel     payal.patel@gmail.com  30.0         HR
38         1039     Tejas Mehta     tejas.mehta@gmail.com  34.0    Finance
39         1040     Shreya Shah     shreya.shah@gmail.com  27.0  Marketing
40         1041  Abhishek Patel  abhishek.patel@gmail.com  29.0         IT
41         1042     Divya Mehta     divya.mehta@gmail.com  26.0         HR
42         1043     Mayank Shah     mayank.shah@gmail.com  33.0    Finance
43         1044    Sonali Patel    sonali.patel@gmail.com  31.0  Marketing
44         1045       Raj Mehta       raj.mehta@gmail.com  40.0         IT
45         1046        Anu Shah        anu.shah@gmail.com  28.0         HR
46         1047       Raj Mehta       raj.mehta@gmail.com  40.0         IT
47         1048      Yash Patel      yash.patel@gmail.com  30.0    Finance

    salary joining_date    status
0    45000   2023-01-15    Active
1    52000   2022-03-20    Active
2    68000   2021-07-10    Active
3    42000   2024-02-12    Active
4    55000   2022-11-01  Inactive
5    48000   2020-08-19    Active
6    61000   2023-05-22    Active
7    47000   2023-09-15    Active
8    75000   2019-04-10    Active
9    58000   2021-12-01  Inactive
10   38000   2024-06-15    Active
11   62000   2022-01-18    Active
12   59000   2020-03-25    Active
13   51000   2023-10-10    Active
15   72000   2021-06-30    Active
16   40000   2024-01-05    Active
17   65000   2018-09-20  Inactive
18   85000   2017-02-14    Active
19   54000   2023-03-11    Active
21   50000   2022-10-01    Active
23   41000   2024-04-20    Active
24   78000   2019-08-15    Active
26   67000   2020-12-10    Active
28   53000   2022-09-01    Active
29   56000   2021-04-16  Inactive
30   71000   2019-10-20    Active
31   43000   2024-03-12    Active
32   95000   2015-07-01    Active
33   60000   2020-01-15    Active
34   64000   2022-06-18    Active
35   39000   2024-05-10    Active
36   82000   2018-03-22    Active
37   57000   2021-09-14    Active
38   69000   2020-07-08    Active
39   45000   2023-11-20    Active
40   58000   2022-02-05    Active
41   51000   2023-06-12    Active
42   73000   2019-12-01    Active
43   48000   2021-05-15    Active
44   88000   2017-11-10    Active
45   52000   2022-08-20    Active
46   88000   2017-11-10    Active
47   66000   2021-03-18    Active

In [23]:
validation_report = errors[
    ["column", "check", "failure_case", "index"]
].copy()

print(validation_report)

         column                                    check       failure_case  \
0         email                             not_nullable                NaN
1         email  str_matches('^[\w\.-]+@[\w\.-]+\.\w+$')  nirav.patel@gmail
2           age                             not_nullable                NaN
3           age                           dtype('int64')                NaN
4           age                         in_range(18, 65)               67.0
5           age                         in_range(18, 65)               17.0
6        salary                          greater_than(0)             -45000
7  joining_date       str_matches('^\d{4}-\d{2}-\d{2}$')       invalid-date
8        status             isin(['Active', 'Inactive'])            Working

   index
0     25
1     22
2     27
3     27
4     20
5     48
6     14
7     49
8     49

In [24]:
validation_report["employee_id"] = validation_report["index"].apply(
    lambda x: df.loc[x, "employee_id"] if pd.notna(x) else None
)

In [25]:
validation_report = validation_report[
    ["employee_id", "column", "check", "failure_case", "index"]
]

print(validation_report)

   employee_id        column                                    check  \
0         1026         email                             not_nullable
1         1023         email  str_matches('^[\w\.-]+@[\w\.-]+\.\w+$')
2         1028           age                             not_nullable
3         1028           age                           dtype('int64')
4         1021           age                         in_range(18, 65)
5         1049           age                         in_range(18, 65)
6         1015        salary                          greater_than(0)
7         1050  joining_date       str_matches('^\d{4}-\d{2}-\d{2}$')
8         1050        status             isin(['Active', 'Inactive'])

        failure_case  index
0                NaN     25
1  nirav.patel@gmail     22
2                NaN     27
3                NaN     27
4               67.0     20
5               17.0     48
6             -45000     14
7       invalid-date     49
8            Working     49

In [26]:
validation_report.to_csv(
    "validation_report.csv",
    index=False
)

In [27]:
duplicate_rows = df[df.duplicated(keep=False)]

print(duplicate_rows)

Empty DataFrame
Columns: [employee_id, employee_name, email, age, department, salary, joining_date, status]
Index: []

In [28]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [29]:
duplicate_employee_data = df.duplicated(
    subset=[
        "employee_name",
        "email",
        "age",
        "department",
        "salary",
        "joining_date",
        "status"
    ],
    keep=False
)

print(df[duplicate_employee_data])

    employee_id employee_name                email   age department  salary  \
44         1045     Raj Mehta  raj.mehta@gmail.com  40.0         IT   88000
46         1047     Raj Mehta  raj.mehta@gmail.com  40.0         IT   88000

   joining_date  status
44   2017-11-10  Active
46   2017-11-10  Active

In [31]:
Check(
    lambda df: (
        (df["status"] == "Inactive") &
        (df["salary"] > 0)
    ).all()
)

In [32]:
df

,employee_id,employee_name,email,age,department,salary,joining_date,status
0,1001,Rahul Shah,rahul.shah@gmail.com,25.0,IT,45000,2023-01-15,Active
1,1002,Priya Patel,priya.patel@gmail.com,28.0,HR,52000,2022-03-20,Active
2,1003,Amit Mehta,amit.mehta@gmail.com,32.0,Finance,68000,2021-07-10,Active
3,1004,Neha Desai,neha.desai@gmail.com,24.0,Marketing,42000,2024-02-12,Active
4,1005,Rohan Shah,rohan.shah@gmail.com,29.0,IT,55000,2022-11-01,Inactive
5,1006,Kajal Patel,kajal.patel@gmail.com,31.0,HR,48000,2020-08-19,Active
6,1007,Jay Mehta,jay.mehta@gmail.com,27.0,Finance,61000,2023-05-22,Active
7,1008,Pooja Shah,pooja.shah@gmail.com,26.0,Marketing,47000,2023-09-15,Active
8,1009,Dev Patel,dev.patel@gmail.com,35.0,IT,75000,2019-04-10,Active
9,1010,Anjali Desai,anjali.desai@gmail.com,30.0,HR,58000,2021-12-01,Inactive
10,1011,Vivek Shah,vivek.shah@gmail.com,22.0,IT,38000,2024-06-15,Active
11,1012,Riya Patel,riya.patel@gmail.com,27.0,Finance,62000,2022-01-18,Active
12,1013,Manish Mehta,manish.mehta@gmail.com,33.0,Marketing,59000,2020-03-25,Active
13,1014,Hetal Shah,hetal.shah@gmail.com,29.0,HR,51000,2023-10-10,Active
14,1015,Akash Patel,akash.patel@gmail.com,26.0,IT,-45000,2022-05-12,Active
15,1016,Simran Mehta,simran.mehta@gmail.com,34.0,Finance,72000,2021-06-30,Active
16,1017,Parth Shah,parth.shah@gmail.com,23.0,Marketing,40000,2024-01-05,Active
17,1018,Nisha Patel,nisha.patel@gmail.com,38.0,HR,65000,2018-09-20,Inactive
18,1019,Kunal Mehta,kunal.mehta@gmail.com,41.0,IT,85000,2017-02-14,Active
19,1020,Diya Shah,diya.shah@gmail.com,25.0,Finance,54000,2023-03-11,Active
20,1021,Arjun Patel,arjun.patel@gmail.com,67.0,IT,90000,2016-05-18,Active
21,1022,Meera Shah,meera.shah@gmail.com,28.0,HR,50000,2022-10-01,Active
22,1023,Nirav Patel,nirav.patel@gmail,30.0,Finance,63000,2021-11-12,Active
23,1024,Krisha Mehta,krisha.mehta@gmail.com,24.0,Marketing,41000,2024-04-20,Active
24,1025,Dhruv Shah,dhruv.shah@gmail.com,36.0,IT,78000,2019-08-15,Active
25,1026,Ankita Patel,NaN,27.0,HR,49000,2023-07-19,Active
26,1027,Harsh Mehta,harsh.mehta@gmail.com,31.0,Finance,67000,2020-12-10,Active
27,1028,Isha Shah,isha.shah@gmail.com,NaN,Marketing,46000,2023-02-25,Active
28,1029,Meet Patel,meet.patel@gmail.com,26.0,IT,53000,2022-09-01,Active
29,1030,Komal Desai,komal.desai@gmail.com,29.0,HR,56000,2021-04-16,Inactive
30,1031,Devang Shah,devang.shah@gmail.com,37.0,Finance,71000,2019-10-20,Active
31,1032,Palak Patel,palak.patel@gmail.com,25.0,Marketing,43000,2024-03-12,Active
32,1033,Chirag Mehta,chirag.mehta@gmail.com,45.0,IT,95000,2015-07-01,Active
33,1034,Reema Shah,reema.shah@gmail.com,32.0,HR,60000,2020-01-15,Active
34,1035,Varun Patel,varun.patel@gmail.com,28.0,Finance,64000,2022-06-18,Active
35,1036,Krupa Mehta,krupa.mehta@gmail.com,23.0,Marketing,39000,2024-05-10,Active
36,1037,Sameer Shah,sameer.shah@gmail.com,39.0,IT,82000,2018-03-22,Active
37,1038,Payal Patel,payal.patel@gmail.com,30.0,HR,57000,2021-09-14,Active
38,1039,Tejas Mehta,tejas.mehta@gmail.com,34.0,Finance,69000,2020-07-08,Active
39,1040,Shreya Shah,shreya.shah@gmail.com,27.0,Marketing,45000,2023-11-20,Active
40,1041,Abhishek Patel,abhishek.patel@gmail.com,29.0,IT,58000,2022-02-05,Active
41,1042,Divya Mehta,divya.mehta@gmail.com,26.0,HR,51000,2023-06-12,Active
42,1043,Mayank Shah,mayank.shah@gmail.com,33.0,Finance,73000,2019-12-01,Active
43,1044,Sonali Patel,sonali.patel@gmail.com,31.0,Marketing,48000,2021-05-15,Active
44,1045,Raj Mehta,raj.mehta@gmail.com,40.0,IT,88000,2017-11-10,Active
45,1046,Anu Shah,anu.shah@gmail.com,28.0,HR,52000,2022-08-20,Active
46,1047,Raj Mehta,raj.mehta@gmail.com,40.0,IT,88000,2017-11-10,Active
47,1048,Yash Patel,yash.patel@gmail.com,30.0,Finance,66000,2021-03-18,Active
48,1049,Mehul Shah,mehul.shah@gmail.com,17.0,Marketing,37000,2024-07-01,Active
49,1050,Krish Patel,krish.patel@gmail.com,27.0,IT,59000,invalid-date,Working

In [33]:
try:
    validated_df = schema.validate(df, lazy=True)

    print("Validation Passed")
    df = validated_df

except pa.errors.SchemaErrors as e:
    print("Validation Failed")

    errors = e.failure_cases

    invalid_indexes = errors["index"].dropna().unique()

    df = df.drop(index=invalid_indexes)

    print("Invalid rows removed")

print(df)

Validation Failed
Invalid rows removed
    employee_id   employee_name                     email   age department  \
0          1001      Rahul Shah      rahul.shah@gmail.com  25.0         IT
1          1002     Priya Patel     priya.patel@gmail.com  28.0         HR
2          1003      Amit Mehta      amit.mehta@gmail.com  32.0    Finance
3          1004      Neha Desai      neha.desai@gmail.com  24.0  Marketing
4          1005      Rohan Shah      rohan.shah@gmail.com  29.0         IT
5          1006     Kajal Patel     kajal.patel@gmail.com  31.0         HR
6          1007       Jay Mehta       jay.mehta@gmail.com  27.0    Finance
7          1008      Pooja Shah      pooja.shah@gmail.com  26.0  Marketing
8          1009       Dev Patel       dev.patel@gmail.com  35.0         IT
9          1010    Anjali Desai    anjali.desai@gmail.com  30.0         HR
10         1011      Vivek Shah      vivek.shah@gmail.com  22.0         IT
11         1012      Riya Patel      riya.patel@gmail.com  27.0    Finance
12         1013    Manish Mehta    manish.mehta@gmail.com  33.0  Marketing
13         1014      Hetal Shah      hetal.shah@gmail.com  29.0         HR
15         1016    Simran Mehta    simran.mehta@gmail.com  34.0    Finance
16         1017      Parth Shah      parth.shah@gmail.com  23.0  Marketing
17         1018     Nisha Patel     nisha.patel@gmail.com  38.0         HR
18         1019     Kunal Mehta     kunal.mehta@gmail.com  41.0         IT
19         1020       Diya Shah       diya.shah@gmail.com  25.0    Finance
21         1022      Meera Shah      meera.shah@gmail.com  28.0         HR
23         1024    Krisha Mehta    krisha.mehta@gmail.com  24.0  Marketing
24         1025      Dhruv Shah      dhruv.shah@gmail.com  36.0         IT
26         1027     Harsh Mehta     harsh.mehta@gmail.com  31.0    Finance
28         1029      Meet Patel      meet.patel@gmail.com  26.0         IT
29         1030     Komal Desai     komal.desai@gmail.com  29.0         HR
30         1031     Devang Shah     devang.shah@gmail.com  37.0    Finance
31         1032     Palak Patel     palak.patel@gmail.com  25.0  Marketing
32         1033    Chirag Mehta    chirag.mehta@gmail.com  45.0         IT
33         1034      Reema Shah      reema.shah@gmail.com  32.0         HR
34         1035     Varun Patel     varun.patel@gmail.com  28.0    Finance
35         1036     Krupa Mehta     krupa.mehta@gmail.com  23.0  Marketing
36         1037     Sameer Shah     sameer.shah@gmail.com  39.0         IT
37         1038     Payal Patel     payal.patel@gmail.com  30.0         HR
38         1039     Tejas Mehta     tejas.mehta@gmail.com  34.0    Finance
39         1040     Shreya Shah     shreya.shah@gmail.com  27.0  Marketing
40         1041  Abhishek Patel  abhishek.patel@gmail.com  29.0         IT
41         1042     Divya Mehta     divya.mehta@gmail.com  26.0         HR
42         1043     Mayank Shah     mayank.shah@gmail.com  33.0    Finance
43         1044    Sonali Patel    sonali.patel@gmail.com  31.0  Marketing
44         1045       Raj Mehta       raj.mehta@gmail.com  40.0         IT
45         1046        Anu Shah        anu.shah@gmail.com  28.0         HR
46         1047       Raj Mehta       raj.mehta@gmail.com  40.0         IT
47         1048      Yash Patel      yash.patel@gmail.com  30.0    Finance

    salary joining_date    status
0    45000   2023-01-15    Active
1    52000   2022-03-20    Active
2    68000   2021-07-10    Active
3    42000   2024-02-12    Active
4    55000   2022-11-01  Inactive
5    48000   2020-08-19    Active
6    61000   2023-05-22    Active
7    47000   2023-09-15    Active
8    75000   2019-04-10    Active
9    58000   2021-12-01  Inactive
10   38000   2024-06-15    Active
11   62000   2022-01-18    Active
12   59000   2020-03-25    Active
13   51000   2023-10-10    Active
15   72000   2021-06-30    Active
16   40000   2024-01-05    Active
17   65000   2018-09-20  Inactive
18   85000   2017-02-14    Active
19   54000   2023-03-11    Active
21   50000   2022-10-01    Active
23   41000   2024-04-20    Active
24   78000   2019-08-15    Active
26   67000   2020-12-10    Active
28   53000   2022-09-01    Active
29   56000   2021-04-16  Inactive
30   71000   2019-10-20    Active
31   43000   2024-03-12    Active
32   95000   2015-07-01    Active
33   60000   2020-01-15    Active
34   64000   2022-06-18    Active
35   39000   2024-05-10    Active
36   82000   2018-03-22    Active
37   57000   2021-09-14    Active
38   69000   2020-07-08    Active
39   45000   2023-11-20    Active
40   58000   2022-02-05    Active
41   51000   2023-06-12    Active
42   73000   2019-12-01    Active
43   48000   2021-05-15    Active
44   88000   2017-11-10    Active
45   52000   2022-08-20    Active
46   88000   2017-11-10    Active
47   66000   2021-03-18    Active

In [34]:
try:
    validated_df = schema.validate(df, lazy=True)

    print("Validation Passed")
    df = validated_df

except pa.errors.SchemaErrors as e:
    print("Validation Failed")

    errors = e.failure_cases

    invalid_indexes = errors["index"].dropna().unique()

    df = df.drop(index=invalid_indexes)

    print("Valid Data:")
    print(df)

Validation Failed
Valid Data:
    employee_id   employee_name                     email   age department  \
0          1001      Rahul Shah      rahul.shah@gmail.com  25.0         IT
1          1002     Priya Patel     priya.patel@gmail.com  28.0         HR
2          1003      Amit Mehta      amit.mehta@gmail.com  32.0    Finance
3          1004      Neha Desai      neha.desai@gmail.com  24.0  Marketing
4          1005      Rohan Shah      rohan.shah@gmail.com  29.0         IT
5          1006     Kajal Patel     kajal.patel@gmail.com  31.0         HR
6          1007       Jay Mehta       jay.mehta@gmail.com  27.0    Finance
7          1008      Pooja Shah      pooja.shah@gmail.com  26.0  Marketing
8          1009       Dev Patel       dev.patel@gmail.com  35.0         IT
9          1010    Anjali Desai    anjali.desai@gmail.com  30.0         HR
10         1011      Vivek Shah      vivek.shah@gmail.com  22.0         IT
11         1012      Riya Patel      riya.patel@gmail.com  27.0    Finance
12         1013    Manish Mehta    manish.mehta@gmail.com  33.0  Marketing
13         1014      Hetal Shah      hetal.shah@gmail.com  29.0         HR
15         1016    Simran Mehta    simran.mehta@gmail.com  34.0    Finance
16         1017      Parth Shah      parth.shah@gmail.com  23.0  Marketing
17         1018     Nisha Patel     nisha.patel@gmail.com  38.0         HR
18         1019     Kunal Mehta     kunal.mehta@gmail.com  41.0         IT
19         1020       Diya Shah       diya.shah@gmail.com  25.0    Finance
21         1022      Meera Shah      meera.shah@gmail.com  28.0         HR
23         1024    Krisha Mehta    krisha.mehta@gmail.com  24.0  Marketing
24         1025      Dhruv Shah      dhruv.shah@gmail.com  36.0         IT
26         1027     Harsh Mehta     harsh.mehta@gmail.com  31.0    Finance
28         1029      Meet Patel      meet.patel@gmail.com  26.0         IT
29         1030     Komal Desai     komal.desai@gmail.com  29.0         HR
30         1031     Devang Shah     devang.shah@gmail.com  37.0    Finance
31         1032     Palak Patel     palak.patel@gmail.com  25.0  Marketing
32         1033    Chirag Mehta    chirag.mehta@gmail.com  45.0         IT
33         1034      Reema Shah      reema.shah@gmail.com  32.0         HR
34         1035     Varun Patel     varun.patel@gmail.com  28.0    Finance
35         1036     Krupa Mehta     krupa.mehta@gmail.com  23.0  Marketing
36         1037     Sameer Shah     sameer.shah@gmail.com  39.0         IT
37         1038     Payal Patel     payal.patel@gmail.com  30.0         HR
38         1039     Tejas Mehta     tejas.mehta@gmail.com  34.0    Finance
39         1040     Shreya Shah     shreya.shah@gmail.com  27.0  Marketing
40         1041  Abhishek Patel  abhishek.patel@gmail.com  29.0         IT
41         1042     Divya Mehta     divya.mehta@gmail.com  26.0         HR
42         1043     Mayank Shah     mayank.shah@gmail.com  33.0    Finance
43         1044    Sonali Patel    sonali.patel@gmail.com  31.0  Marketing
44         1045       Raj Mehta       raj.mehta@gmail.com  40.0         IT
45         1046        Anu Shah        anu.shah@gmail.com  28.0         HR
46         1047       Raj Mehta       raj.mehta@gmail.com  40.0         IT
47         1048      Yash Patel      yash.patel@gmail.com  30.0    Finance

    salary joining_date    status
0    45000   2023-01-15    Active
1    52000   2022-03-20    Active
2    68000   2021-07-10    Active
3    42000   2024-02-12    Active
4    55000   2022-11-01  Inactive
5    48000   2020-08-19    Active
6    61000   2023-05-22    Active
7    47000   2023-09-15    Active
8    75000   2019-04-10    Active
9    58000   2021-12-01  Inactive
10   38000   2024-06-15    Active
11   62000   2022-01-18    Active
12   59000   2020-03-25    Active
13   51000   2023-10-10    Active
15   72000   2021-06-30    Active
16   40000   2024-01-05    Active
17   65000   2018-09-20  Inactive
18   85000   2017-02-14    Active
19   54000   2023-03-11    Active
21   50000   2022-10-01    Active
23   41000   2024-04-20    Active
24   78000   2019-08-15    Active
26   67000   2020-12-10    Active
28   53000   2022-09-01    Active
29   56000   2021-04-16  Inactive
30   71000   2019-10-20    Active
31   43000   2024-03-12    Active
32   95000   2015-07-01    Active
33   60000   2020-01-15    Active
34   64000   2022-06-18    Active
35   39000   2024-05-10    Active
36   82000   2018-03-22    Active
37   57000   2021-09-14    Active
38   69000   2020-07-08    Active
39   45000   2023-11-20    Active
40   58000   2022-02-05    Active
41   51000   2023-06-12    Active
42   73000   2019-12-01    Active
43   48000   2021-05-15    Active
44   88000   2017-11-10    Active
45   52000   2022-08-20    Active
46   88000   2017-11-10    Active
47   66000   2021-03-18    Active

In [35]:
df

,employee_id,employee_name,email,age,department,salary,joining_date,status
0,1001,Rahul Shah,rahul.shah@gmail.com,25.0,IT,45000,2023-01-15,Active
1,1002,Priya Patel,priya.patel@gmail.com,28.0,HR,52000,2022-03-20,Active
2,1003,Amit Mehta,amit.mehta@gmail.com,32.0,Finance,68000,2021-07-10,Active
3,1004,Neha Desai,neha.desai@gmail.com,24.0,Marketing,42000,2024-02-12,Active
4,1005,Rohan Shah,rohan.shah@gmail.com,29.0,IT,55000,2022-11-01,Inactive
5,1006,Kajal Patel,kajal.patel@gmail.com,31.0,HR,48000,2020-08-19,Active
6,1007,Jay Mehta,jay.mehta@gmail.com,27.0,Finance,61000,2023-05-22,Active
7,1008,Pooja Shah,pooja.shah@gmail.com,26.0,Marketing,47000,2023-09-15,Active
8,1009,Dev Patel,dev.patel@gmail.com,35.0,IT,75000,2019-04-10,Active
9,1010,Anjali Desai,anjali.desai@gmail.com,30.0,HR,58000,2021-12-01,Inactive
10,1011,Vivek Shah,vivek.shah@gmail.com,22.0,IT,38000,2024-06-15,Active
11,1012,Riya Patel,riya.patel@gmail.com,27.0,Finance,62000,2022-01-18,Active
12,1013,Manish Mehta,manish.mehta@gmail.com,33.0,Marketing,59000,2020-03-25,Active
13,1014,Hetal Shah,hetal.shah@gmail.com,29.0,HR,51000,2023-10-10,Active
15,1016,Simran Mehta,simran.mehta@gmail.com,34.0,Finance,72000,2021-06-30,Active
16,1017,Parth Shah,parth.shah@gmail.com,23.0,Marketing,40000,2024-01-05,Active
17,1018,Nisha Patel,nisha.patel@gmail.com,38.0,HR,65000,2018-09-20,Inactive
18,1019,Kunal Mehta,kunal.mehta@gmail.com,41.0,IT,85000,2017-02-14,Active
19,1020,Diya Shah,diya.shah@gmail.com,25.0,Finance,54000,2023-03-11,Active
21,1022,Meera Shah,meera.shah@gmail.com,28.0,HR,50000,2022-10-01,Active
23,1024,Krisha Mehta,krisha.mehta@gmail.com,24.0,Marketing,41000,2024-04-20,Active
24,1025,Dhruv Shah,dhruv.shah@gmail.com,36.0,IT,78000,2019-08-15,Active
26,1027,Harsh Mehta,harsh.mehta@gmail.com,31.0,Finance,67000,2020-12-10,Active
28,1029,Meet Patel,meet.patel@gmail.com,26.0,IT,53000,2022-09-01,Active
29,1030,Komal Desai,komal.desai@gmail.com,29.0,HR,56000,2021-04-16,Inactive
30,1031,Devang Shah,devang.shah@gmail.com,37.0,Finance,71000,2019-10-20,Active
31,1032,Palak Patel,palak.patel@gmail.com,25.0,Marketing,43000,2024-03-12,Active
32,1033,Chirag Mehta,chirag.mehta@gmail.com,45.0,IT,95000,2015-07-01,Active
33,1034,Reema Shah,reema.shah@gmail.com,32.0,HR,60000,2020-01-15,Active
34,1035,Varun Patel,varun.patel@gmail.com,28.0,Finance,64000,2022-06-18,Active
35,1036,Krupa Mehta,krupa.mehta@gmail.com,23.0,Marketing,39000,2024-05-10,Active
36,1037,Sameer Shah,sameer.shah@gmail.com,39.0,IT,82000,2018-03-22,Active
37,1038,Payal Patel,payal.patel@gmail.com,30.0,HR,57000,2021-09-14,Active
38,1039,Tejas Mehta,tejas.mehta@gmail.com,34.0,Finance,69000,2020-07-08,Active
39,1040,Shreya Shah,shreya.shah@gmail.com,27.0,Marketing,45000,2023-11-20,Active
40,1041,Abhishek Patel,abhishek.patel@gmail.com,29.0,IT,58000,2022-02-05,Active
41,1042,Divya Mehta,divya.mehta@gmail.com,26.0,HR,51000,2023-06-12,Active
42,1043,Mayank Shah,mayank.shah@gmail.com,33.0,Finance,73000,2019-12-01,Active
43,1044,Sonali Patel,sonali.patel@gmail.com,31.0,Marketing,48000,2021-05-15,Active
44,1045,Raj Mehta,raj.mehta@gmail.com,40.0,IT,88000,2017-11-10,Active
45,1046,Anu Shah,anu.shah@gmail.com,28.0,HR,52000,2022-08-20,Active
46,1047,Raj Mehta,raj.mehta@gmail.com,40.0,IT,88000,2017-11-10,Active
47,1048,Yash Patel,yash.patel@gmail.com,30.0,Finance,66000,2021-03-18,Active

In [37]:
try:
    validated_df = schema.validate(df, lazy=True)

    print("Validation Passed")
    df = validated_df

except pa.errors.SchemaErrors as e:

    print("Validation Failed")

    errors = e.failure_cases

    # Log validation errors
    logger.error("Data validation failed")

    for _, row in errors.iterrows():
        logger.error(
            f"Column: {row['column']} | "
            f"Check: {row['check']} | "
            f"Value: {row['failure_case']} | "
            f"Index: {row['index']}"
        )

    # Get invalid rows
    invalid_indexes = errors["index"].dropna().unique()

    # Keep only valid rows
    df = df.drop(index=invalid_indexes)

    print("Invalid rows:", len(invalid_indexes))
    print("Valid Data:")
    print(df)

Validation Failed
Invalid rows: 0
Valid Data:
    employee_id   employee_name                     email   age department  \
0          1001      Rahul Shah      rahul.shah@gmail.com  25.0         IT
1          1002     Priya Patel     priya.patel@gmail.com  28.0         HR
2          1003      Amit Mehta      amit.mehta@gmail.com  32.0    Finance
3          1004      Neha Desai      neha.desai@gmail.com  24.0  Marketing
4          1005      Rohan Shah      rohan.shah@gmail.com  29.0         IT
5          1006     Kajal Patel     kajal.patel@gmail.com  31.0         HR
6          1007       Jay Mehta       jay.mehta@gmail.com  27.0    Finance
7          1008      Pooja Shah      pooja.shah@gmail.com  26.0  Marketing
8          1009       Dev Patel       dev.patel@gmail.com  35.0         IT
9          1010    Anjali Desai    anjali.desai@gmail.com  30.0         HR
10         1011      Vivek Shah      vivek.shah@gmail.com  22.0         IT
11         1012      Riya Patel      riya.patel@gmail.com  27.0    Finance
12         1013    Manish Mehta    manish.mehta@gmail.com  33.0  Marketing
13         1014      Hetal Shah      hetal.shah@gmail.com  29.0         HR
15         1016    Simran Mehta    simran.mehta@gmail.com  34.0    Finance
16         1017      Parth Shah      parth.shah@gmail.com  23.0  Marketing
17         1018     Nisha Patel     nisha.patel@gmail.com  38.0         HR
18         1019     Kunal Mehta     kunal.mehta@gmail.com  41.0         IT
19         1020       Diya Shah       diya.shah@gmail.com  25.0    Finance
21         1022      Meera Shah      meera.shah@gmail.com  28.0         HR
23         1024    Krisha Mehta    krisha.mehta@gmail.com  24.0  Marketing
24         1025      Dhruv Shah      dhruv.shah@gmail.com  36.0         IT
26         1027     Harsh Mehta     harsh.mehta@gmail.com  31.0    Finance
28         1029      Meet Patel      meet.patel@gmail.com  26.0         IT
29         1030     Komal Desai     komal.desai@gmail.com  29.0         HR
30         1031     Devang Shah     devang.shah@gmail.com  37.0    Finance
31         1032     Palak Patel     palak.patel@gmail.com  25.0  Marketing
32         1033    Chirag Mehta    chirag.mehta@gmail.com  45.0         IT
33         1034      Reema Shah      reema.shah@gmail.com  32.0         HR
34         1035     Varun Patel     varun.patel@gmail.com  28.0    Finance
35         1036     Krupa Mehta     krupa.mehta@gmail.com  23.0  Marketing
36         1037     Sameer Shah     sameer.shah@gmail.com  39.0         IT
37         1038     Payal Patel     payal.patel@gmail.com  30.0         HR
38         1039     Tejas Mehta     tejas.mehta@gmail.com  34.0    Finance
39         1040     Shreya Shah     shreya.shah@gmail.com  27.0  Marketing
40         1041  Abhishek Patel  abhishek.patel@gmail.com  29.0         IT
41         1042     Divya Mehta     divya.mehta@gmail.com  26.0         HR
42         1043     Mayank Shah     mayank.shah@gmail.com  33.0    Finance
43         1044    Sonali Patel    sonali.patel@gmail.com  31.0  Marketing
44         1045       Raj Mehta       raj.mehta@gmail.com  40.0         IT
45         1046        Anu Shah        anu.shah@gmail.com  28.0         HR
46         1047       Raj Mehta       raj.mehta@gmail.com  40.0         IT
47         1048      Yash Patel      yash.patel@gmail.com  30.0    Finance

    salary joining_date    status
0    45000   2023-01-15    Active
1    52000   2022-03-20    Active
2    68000   2021-07-10    Active
3    42000   2024-02-12    Active
4    55000   2022-11-01  Inactive
5    48000   2020-08-19    Active
6    61000   2023-05-22    Active
7    47000   2023-09-15    Active
8    75000   2019-04-10    Active
9    58000   2021-12-01  Inactive
10   38000   2024-06-15    Active
11   62000   2022-01-18    Active
12   59000   2020-03-25    Active
13   51000   2023-10-10    Active
15   72000   2021-06-30    Active
16   40000   2024-01-05    Active
17   65000   2018-09-20  Inactive
18   85000   2017-02-14    Active
19   54000   2023-03-11    Active
21   50000   2022-10-01    Active
23   41000   2024-04-20    Active
24   78000   2019-08-15    Active
26   67000   2020-12-10    Active
28   53000   2022-09-01    Active
29   56000   2021-04-16  Inactive
30   71000   2019-10-20    Active
31   43000   2024-03-12    Active
32   95000   2015-07-01    Active
33   60000   2020-01-15    Active
34   64000   2022-06-18    Active
35   39000   2024-05-10    Active
36   82000   2018-03-22    Active
37   57000   2021-09-14    Active
38   69000   2020-07-08    Active
39   45000   2023-11-20    Active
40   58000   2022-02-05    Active
41   51000   2023-06-12    Active
42   73000   2019-12-01    Active
43   48000   2021-05-15    Active
44   88000   2017-11-10    Active
45   52000   2022-08-20    Active
46   88000   2017-11-10    Active
47   66000   2021-03-18    Active