In [242]:
import pandas as pd

dep = pd.read_csv("departments.csv")
emp = pd.read_csv("employees.csv")

In [243]:
emp

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status
0,1001,Aarav Shah,D01,24.0,45000,2023-01-15,Surat,Active
1,1002,Diya Patel,D02,27.0,52000,15/02/2022,Ahmedabad,Active
2,1003,Rohan Mehta,D03,29.0,60000,2021-07-10,Mumbai,Active
3,1004,Mira Joshi,D01,26.0,48000,2022-11-01,Surat,Active
4,1005,Kabir Desai,D04,31.0,72000,2020-03-18,Pune,Active
5,1006,Isha Trivedi,D02,25.0,51000,2023/04/21,Vadodara,Active
6,1007,Vivaan Shah,D05,28.0,65000,2021-09-05,Bengaluru,Inactive
7,1008,Anaya Mehta,D03,30.0,68000,2020-12-11,Mumbai,Active
8,1009,Arjun Patel,D01,23.0,42000,2024-01-08,Surat,Active
9,1010,Kiara Desai,D04,32.0,75000,2019-06-25,Pune,Active
10,1011,Dev Shah,D02,26.0,50000,2022-08-19,Ahmedabad,Active
11,1012,Sara Khan,D06,29.0,58000,2021-10-30,Delhi,Active
12,1013,Yashvi Patel,D03,27.0,62000,2023-02-14,Mumbai,Active
13,1014,Manav Joshi,D01,35.0,85000,2018-05-17,Surat,Active
14,1015,Riya Mehta,D05,24.0,"47,000",2024-03-01,Bengaluru,Active
15,1016,Neil Desai,D04,33.0,80000,2020-09-12,Pune,Active
16,1017,Aditi Shah,D02,28.0,54000,2022-01-20,Ahmedabad,Active
17,1018,Om Patel,D03,26.0,61000,2023-06-07,Mumbai,Active
18,1019,Nisha Joshi,D07,30.0,59000,2021-04-16,Jaipur,Active
19,1020,Reyansh Mehta,D01,22.0,39000,2024-05-10,Surat,Active
20,1021,Tara Desai,D05,27.0,67000,2022-07-22,Bengaluru,Inactive
21,1022,Vivaan Shah,D05,28.0,65000,2021-09-05,Bengaluru,Inactive
22,1023,Aarav Shah,D01,24.0,45000,2023-01-15,Surat,Active
23,1024,Pooja Patel,NaN,29.0,56000,2022-10-09,Ahmedabad,Active
24,1025,Kunal Mehta,D08,34.0,NaN,2019-11-11,Mumbai,Active
25,1026,Rahul Shah,D02,NaN,49000,2023-08-14,Ahmedabad,Active
26,1027,Neha Patel,D03,31.0,63000,NaN,Mumbai,Active
27,1028,Jay Joshi,D01,25.0,44000,2024-02-18,NaN,Active
28,1029,Priya Desai,D04,30.0,71000,2020-06-21,Pune,Active
29,1030,Harsh Mehta,D05,27.0,66000,2022-03-11,Bengaluru,Active
30,1031,Meera Shah,D02,26.0,53000,2023-05-19,Ahmedabad,Active
31,1032,Ravi Patel,d03,29.0,59000,2021-12-01,Mumbai,Active
32,1033,Simran Joshi,D01,28.0,55000,2022-09-15,Surat,Active
33,1034,Akash Desai,D04,36.0,90000,2018-07-20,Pune,Active
34,1035,Divya Mehta,D05,24.0,48000,2024-01-25,Bengaluru,Active
35,1036,Karan Shah,D06,32.0,61000,2020-10-10,Delhi,Inactive
36,1037,Anjali Patel,D03,27.0,62000,2023-03-05,Mumbai,Active
37,1038,Mohit Joshi,D01,33.0,78000,2019-04-17,Surat,Active
38,1039,Sneha Desai,D04,29.0,69000,2021-08-09,Pune,Active
39,1040,Varun Mehta,D05,31.0,73000,2020-01-13,Bengaluru,Active
40,1041,Rahul Shah,D02,NaN,49000,2023-08-14,Ahmedabad,Active
41,1042,Heena Patel,D03,26.0,58000,2022-06-16,Mumbai,Active
42,1043,Parth Joshi,D01,24.0,41000,2024-04-12,Surat,Active
43,1044,Nidhi Desai,D04,28.0,64000,2022-11-30,Pune,Active
44,1045,Krish Mehta,D05,30.0,70000,2021-05-18,Bengaluru,Active
45,1046,Maulik Shah,D06,35.0,76000,2019-09-23,Delhi,Active
46,1047,Hetal Patel,D03,27.0,"62,000",2023-03-05,Mumbai,Active
47,1048,Parth Joshi,D01,24.0,41000,2024-04-12,Surat,Active
48,1049,Unknown,D99,40.0,100000,2020-01-01,Unknown,Active
49,1050,Devika Shah,D02,29.0,57000,2022-02-28,Ahmedabad,Active

In [244]:
dep

   dept_id           department_name   location        manager annual_budget
0      D01               Engineering      Surat    Rajesh Shah      12000000
1      D02           Human Resources  Ahmedabad     Neha Patel       6500000
2      D03                   Finance     Mumbai     Amit Mehta       8000000
3      D04                     Sales       Pune    Priya Desai      10000000
4      D05                 Marketing  Bengaluru    Karan Joshi       9000000
5      D06                Operations      Delhi   Sanjay Kumar       7500000
6      D07          Customer Support     Jaipur   Meena Sharma       6000000
7      D08  Research and Development     Mumbai     Vikram Rao      11000000
8      D09                     Legal  Ahmedabad     Nitin Shah       5000000
9      D10                IT Support      Surat    Komal Patel       5500000
10     D11               Procurement   Vadodara   Rakesh Joshi       4500000
11     D12         Quality Assurance       Pune    Sneha Desai       7000000
12     D13      Business Development      Delhi   Arvind Patel       8500000
13     D14            Data Analytics     Mumbai     Pinal Shah       9500000
14     D15            Administration      Surat  Jignesh Patel       4000000
15     D16                  Security  Bengaluru      Mohan Rao       3500000
16     D17                  Training  Ahmedabad     Hetal Shah       3000000
17     D18                   Product       Pune     Rina Mehta      10500000
18     D19                    Design     Mumbai   Nirali Joshi       6200000
19     D20                Compliance      Delhi  Bhavesh Patel       4800000
20     D21                 Logistics   Vadodara     Dhruv Shah       7200000
21     D22                  Strategy      Surat    Mansi Mehta       9000000
22     D23                Operations  Bengaluru      Mohan Rao       3500000
23     D24         Corporate Affairs  Ahmedabad            NaN       5200000
24     D25               Engineering      Surat    Rajesh Shah      12000000
25     D26                   Finance     Mumbai     Amit Mehta       8000000
26     D27                 Marketing  Bengaluru    Karan Joshi       9000000
27     D28                     Sales       Pune    Priya Desai      10000000
28     D29           Human Resources  Ahmedabad     Neha Patel       6500000
29     D30          Customer Support     Jaipur   Meena Sharma       6000000
30     D31               Engineering      Surat    Rajesh Shah      12000000
31     D32                   Finance     Mumbai     Amit Mehta       8000000
32     D33                IT Support      Surat    Komal Patel       5500000
33     D34            Data Analytics     Mumbai     Pinal Shah       9500000
34     D35               Procurement   Vadodara   Rakesh Joshi       4500000
35     D36         Quality Assurance       Pune    Sneha Desai       7000000
36     D37                    Design     Mumbai   Nirali Joshi       6200000
37     D38                   Product       Pune     Rina Mehta      10500000
38     D39                Operations      Delhi   Sanjay Kumar       7500000
39     D40                     Legal  Ahmedabad     Nitin Shah       5000000
40     D41                  Training  Ahmedabad     Hetal Shah       3000000
41     D42            Administration      Surat  Jignesh Patel       4000000
42     D43                 Logistics   Vadodara     Dhruv Shah       7200000
43     D44                  Strategy      Surat    Mansi Mehta       9000000
44     D45                  Security  Bengaluru      Mohan Rao       3500000
45     D46  Research and Development     Mumbai     Vikram Rao      11000000
46     D47         Corporate Affairs  Ahmedabad            NaN       5200000
47     D48                     Sales       Pune    Priya Desai    10,000,000
48     D49                   Finance     Mumbai     Amit Mehta       8000000
49     D50               Engineering      Surat    Rajesh Shah      12000000

In [245]:
df = pd.merge(emp , dep , on="dept_id" , how="left")
df

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,D01,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,D02,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,D03,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,D01,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,D04,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000
5,1006,Isha Trivedi,D02,25.0,51000,2023/04/21,Vadodara,Active,Human Resources,Ahmedabad,Neha Patel,6500000
6,1007,Vivaan Shah,D05,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
7,1008,Anaya Mehta,D03,30.0,68000,2020-12-11,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
8,1009,Arjun Patel,D01,23.0,42000,2024-01-08,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
9,1010,Kiara Desai,D04,32.0,75000,2019-06-25,Pune,Active,Sales,Pune,Priya Desai,10000000
10,1011,Dev Shah,D02,26.0,50000,2022-08-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
11,1012,Sara Khan,D06,29.0,58000,2021-10-30,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
12,1013,Yashvi Patel,D03,27.0,62000,2023-02-14,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
13,1014,Manav Joshi,D01,35.0,85000,2018-05-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
14,1015,Riya Mehta,D05,24.0,"47,000",2024-03-01,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
15,1016,Neil Desai,D04,33.0,80000,2020-09-12,Pune,Active,Sales,Pune,Priya Desai,10000000
16,1017,Aditi Shah,D02,28.0,54000,2022-01-20,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
17,1018,Om Patel,D03,26.0,61000,2023-06-07,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
18,1019,Nisha Joshi,D07,30.0,59000,2021-04-16,Jaipur,Active,Customer Support,Jaipur,Meena Sharma,6000000
19,1020,Reyansh Mehta,D01,22.0,39000,2024-05-10,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
20,1021,Tara Desai,D05,27.0,67000,2022-07-22,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
21,1022,Vivaan Shah,D05,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
22,1023,Aarav Shah,D01,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
23,1024,Pooja Patel,NaN,29.0,56000,2022-10-09,Ahmedabad,Active,NaN,NaN,NaN,NaN
24,1025,Kunal Mehta,D08,34.0,NaN,2019-11-11,Mumbai,Active,Research and Development,Mumbai,Vikram Rao,11000000
25,1026,Rahul Shah,D02,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
26,1027,Neha Patel,D03,31.0,63000,NaN,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
27,1028,Jay Joshi,D01,25.0,44000,2024-02-18,NaN,Active,Engineering,Surat,Rajesh Shah,12000000
28,1029,Priya Desai,D04,30.0,71000,2020-06-21,Pune,Active,Sales,Pune,Priya Desai,10000000
29,1030,Harsh Mehta,D05,27.0,66000,2022-03-11,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
30,1031,Meera Shah,D02,26.0,53000,2023-05-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
31,1032,Ravi Patel,d03,29.0,59000,2021-12-01,Mumbai,Active,NaN,NaN,NaN,NaN
32,1033,Simran Joshi,D01,28.0,55000,2022-09-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
33,1034,Akash Desai,D04,36.0,90000,2018-07-20,Pune,Active,Sales,Pune,Priya Desai,10000000
34,1035,Divya Mehta,D05,24.0,48000,2024-01-25,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
35,1036,Karan Shah,D06,32.0,61000,2020-10-10,Delhi,Inactive,Operations,Delhi,Sanjay Kumar,7500000
36,1037,Anjali Patel,D03,27.0,62000,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
37,1038,Mohit Joshi,D01,33.0,78000,2019-04-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
38,1039,Sneha Desai,D04,29.0,69000,2021-08-09,Pune,Active,Sales,Pune,Priya Desai,10000000
39,1040,Varun Mehta,D05,31.0,73000,2020-01-13,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
40,1041,Rahul Shah,D02,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
41,1042,Heena Patel,D03,26.0,58000,2022-06-16,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
42,1043,Parth Joshi,D01,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
43,1044,Nidhi Desai,D04,28.0,64000,2022-11-30,Pune,Active,Sales,Pune,Priya Desai,10000000
44,1045,Krish Mehta,D05,30.0,70000,2021-05-18,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
45,1046,Maulik Shah,D06,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
46,1047,Hetal Patel,D03,27.0,"62,000",2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
47,1048,Parth Joshi,D01,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
48,1049,Unknown,D99,40.0,100000,2020-01-01,Unknown,Active,NaN,NaN,NaN,NaN
49,1050,Devika Shah,D02,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [246]:
df.shape

(50, 12)

In [247]:
df.head()

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,D01,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,D02,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,D03,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,D01,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,D04,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000

In [248]:
df.tail()

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
45,1046,Maulik Shah,D06,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
46,1047,Hetal Patel,D03,27.0,"62,000",2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
47,1048,Parth Joshi,D01,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
48,1049,Unknown,D99,40.0,100000,2020-01-01,Unknown,Active,NaN,NaN,NaN,NaN
49,1050,Devika Shah,D02,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [249]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      50 non-null     int64
 1   employee_name    50 non-null     str
 2   dept_id          49 non-null     str
 3   age              48 non-null     float64
 4   salary           49 non-null     str
 5   joining_date     49 non-null     str
 6   city             49 non-null     str
 7   status           50 non-null     str
 8   department_name  47 non-null     str
 9   location         47 non-null     str
 10  manager          47 non-null     str
 11  annual_budget    47 non-null     str
dtypes: float64(1), int64(1), str(10)
memory usage: 8.5 KB

In [250]:
df.describe()

       employee_id        age
count     50.00000  48.000000
mean    1025.50000  28.500000
std       14.57738   3.753013
min     1001.00000  22.000000
25%     1013.25000  26.000000
50%     1025.50000  28.000000
75%     1037.75000  30.250000
max     1050.00000  40.000000

In [251]:
df.isnull()

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,True,False,False,False,False,False,True,True,True,True
24,False,False,False,False,True,False,False,False,False,False,False,False
25,False,False,False,True,False,False,False,False,False,False,False,False
26,False,False,False,False,False,True,False,False,False,False,False,False
27,False,False,False,False,False,False,True,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,True,True,True,True
32,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,True,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,True,True,True,True
49,False,False,False,False,False,False,False,False,False,False,False,False

In [252]:
df.isnull().sum()

employee_id        0
employee_name      0
dept_id            1
age                2
salary             1
joining_date       1
city               1
status             0
department_name    3
location           3
manager            3
annual_budget      3
dtype: int64

In [253]:
df.isnull().mean()*100

employee_id        0.0
employee_name      0.0
dept_id            2.0
age                4.0
salary             2.0
joining_date       2.0
city               2.0
status             0.0
department_name    6.0
location           6.0
manager            6.0
annual_budget      6.0
dtype: float64

In [254]:
df.dept_id.dtype

In [255]:
df = df.dropna(subset=["dept_id"])

In [256]:
df["dept_id"] = df["dept_id"].str.upper()
df

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,D01,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,D02,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,D03,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,D01,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,D04,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000
5,1006,Isha Trivedi,D02,25.0,51000,2023/04/21,Vadodara,Active,Human Resources,Ahmedabad,Neha Patel,6500000
6,1007,Vivaan Shah,D05,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
7,1008,Anaya Mehta,D03,30.0,68000,2020-12-11,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
8,1009,Arjun Patel,D01,23.0,42000,2024-01-08,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
9,1010,Kiara Desai,D04,32.0,75000,2019-06-25,Pune,Active,Sales,Pune,Priya Desai,10000000
10,1011,Dev Shah,D02,26.0,50000,2022-08-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
11,1012,Sara Khan,D06,29.0,58000,2021-10-30,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
12,1013,Yashvi Patel,D03,27.0,62000,2023-02-14,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
13,1014,Manav Joshi,D01,35.0,85000,2018-05-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
14,1015,Riya Mehta,D05,24.0,"47,000",2024-03-01,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
15,1016,Neil Desai,D04,33.0,80000,2020-09-12,Pune,Active,Sales,Pune,Priya Desai,10000000
16,1017,Aditi Shah,D02,28.0,54000,2022-01-20,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
17,1018,Om Patel,D03,26.0,61000,2023-06-07,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
18,1019,Nisha Joshi,D07,30.0,59000,2021-04-16,Jaipur,Active,Customer Support,Jaipur,Meena Sharma,6000000
19,1020,Reyansh Mehta,D01,22.0,39000,2024-05-10,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
20,1021,Tara Desai,D05,27.0,67000,2022-07-22,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
21,1022,Vivaan Shah,D05,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
22,1023,Aarav Shah,D01,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
24,1025,Kunal Mehta,D08,34.0,NaN,2019-11-11,Mumbai,Active,Research and Development,Mumbai,Vikram Rao,11000000
25,1026,Rahul Shah,D02,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
26,1027,Neha Patel,D03,31.0,63000,NaN,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
27,1028,Jay Joshi,D01,25.0,44000,2024-02-18,NaN,Active,Engineering,Surat,Rajesh Shah,12000000
28,1029,Priya Desai,D04,30.0,71000,2020-06-21,Pune,Active,Sales,Pune,Priya Desai,10000000
29,1030,Harsh Mehta,D05,27.0,66000,2022-03-11,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
30,1031,Meera Shah,D02,26.0,53000,2023-05-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
31,1032,Ravi Patel,D03,29.0,59000,2021-12-01,Mumbai,Active,NaN,NaN,NaN,NaN
32,1033,Simran Joshi,D01,28.0,55000,2022-09-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
33,1034,Akash Desai,D04,36.0,90000,2018-07-20,Pune,Active,Sales,Pune,Priya Desai,10000000
34,1035,Divya Mehta,D05,24.0,48000,2024-01-25,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
35,1036,Karan Shah,D06,32.0,61000,2020-10-10,Delhi,Inactive,Operations,Delhi,Sanjay Kumar,7500000
36,1037,Anjali Patel,D03,27.0,62000,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
37,1038,Mohit Joshi,D01,33.0,78000,2019-04-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
38,1039,Sneha Desai,D04,29.0,69000,2021-08-09,Pune,Active,Sales,Pune,Priya Desai,10000000
39,1040,Varun Mehta,D05,31.0,73000,2020-01-13,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
40,1041,Rahul Shah,D02,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
41,1042,Heena Patel,D03,26.0,58000,2022-06-16,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
42,1043,Parth Joshi,D01,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
43,1044,Nidhi Desai,D04,28.0,64000,2022-11-30,Pune,Active,Sales,Pune,Priya Desai,10000000
44,1045,Krish Mehta,D05,30.0,70000,2021-05-18,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
45,1046,Maulik Shah,D06,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
46,1047,Hetal Patel,D03,27.0,"62,000",2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
47,1048,Parth Joshi,D01,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
48,1049,Unknown,D99,40.0,100000,2020-01-01,Unknown,Active,NaN,NaN,NaN,NaN
49,1050,Devika Shah,D02,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [257]:
df["dept_id"].unique()

<ArrowStringArray>
['D01', 'D02', 'D03', 'D04', 'D05', 'D06', 'D07', 'D08', 'D99']
Length: 9, dtype: str

In [258]:
df["dept_id"] = df["dept_id"].str.replace("D", "",regex=False).astype(int)
df

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,2,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000
5,1006,Isha Trivedi,2,25.0,51000,2023/04/21,Vadodara,Active,Human Resources,Ahmedabad,Neha Patel,6500000
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,Pune,Active,Sales,Pune,Priya Desai,10000000
10,1011,Dev Shah,2,26.0,50000,2022-08-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
11,1012,Sara Khan,6,29.0,58000,2021-10-30,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
14,1015,Riya Mehta,5,24.0,"47,000",2024-03-01,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
15,1016,Neil Desai,4,33.0,80000,2020-09-12,Pune,Active,Sales,Pune,Priya Desai,10000000
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
17,1018,Om Patel,3,26.0,61000,2023-06-07,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,Jaipur,Active,Customer Support,Jaipur,Meena Sharma,6000000
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
20,1021,Tara Desai,5,27.0,67000,2022-07-22,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
24,1025,Kunal Mehta,8,34.0,NaN,2019-11-11,Mumbai,Active,Research and Development,Mumbai,Vikram Rao,11000000
25,1026,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
26,1027,Neha Patel,3,31.0,63000,NaN,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,NaN,Active,Engineering,Surat,Rajesh Shah,12000000
28,1029,Priya Desai,4,30.0,71000,2020-06-21,Pune,Active,Sales,Pune,Priya Desai,10000000
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
30,1031,Meera Shah,2,26.0,53000,2023-05-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
31,1032,Ravi Patel,3,29.0,59000,2021-12-01,Mumbai,Active,NaN,NaN,NaN,NaN
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
33,1034,Akash Desai,4,36.0,90000,2018-07-20,Pune,Active,Sales,Pune,Priya Desai,10000000
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
35,1036,Karan Shah,6,32.0,61000,2020-10-10,Delhi,Inactive,Operations,Delhi,Sanjay Kumar,7500000
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,Pune,Active,Sales,Pune,Priya Desai,10000000
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
40,1041,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
41,1042,Heena Patel,3,26.0,58000,2022-06-16,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,Pune,Active,Sales,Pune,Priya Desai,10000000
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
46,1047,Hetal Patel,3,27.0,"62,000",2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
48,1049,Unknown,99,40.0,100000,2020-01-01,Unknown,Active,NaN,NaN,NaN,NaN
49,1050,Devika Shah,2,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [259]:
df["dept_id"].dtype

dtype('int64')

In [260]:
df["department_name"].isnull().sum()

np.int64(2)

In [261]:
df = df.dropna(subset=["department_name"])
df

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,2,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000
5,1006,Isha Trivedi,2,25.0,51000,2023/04/21,Vadodara,Active,Human Resources,Ahmedabad,Neha Patel,6500000
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,Pune,Active,Sales,Pune,Priya Desai,10000000
10,1011,Dev Shah,2,26.0,50000,2022-08-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
11,1012,Sara Khan,6,29.0,58000,2021-10-30,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
14,1015,Riya Mehta,5,24.0,"47,000",2024-03-01,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
15,1016,Neil Desai,4,33.0,80000,2020-09-12,Pune,Active,Sales,Pune,Priya Desai,10000000
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
17,1018,Om Patel,3,26.0,61000,2023-06-07,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,Jaipur,Active,Customer Support,Jaipur,Meena Sharma,6000000
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
20,1021,Tara Desai,5,27.0,67000,2022-07-22,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
24,1025,Kunal Mehta,8,34.0,NaN,2019-11-11,Mumbai,Active,Research and Development,Mumbai,Vikram Rao,11000000
25,1026,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
26,1027,Neha Patel,3,31.0,63000,NaN,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,NaN,Active,Engineering,Surat,Rajesh Shah,12000000
28,1029,Priya Desai,4,30.0,71000,2020-06-21,Pune,Active,Sales,Pune,Priya Desai,10000000
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
30,1031,Meera Shah,2,26.0,53000,2023-05-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
33,1034,Akash Desai,4,36.0,90000,2018-07-20,Pune,Active,Sales,Pune,Priya Desai,10000000
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
35,1036,Karan Shah,6,32.0,61000,2020-10-10,Delhi,Inactive,Operations,Delhi,Sanjay Kumar,7500000
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,Pune,Active,Sales,Pune,Priya Desai,10000000
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
40,1041,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
41,1042,Heena Patel,3,26.0,58000,2022-06-16,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,Pune,Active,Sales,Pune,Priya Desai,10000000
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
46,1047,Hetal Patel,3,27.0,"62,000",2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
49,1050,Devika Shah,2,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [262]:
df["department_name"].isnull().sum()

np.int64(0)

In [263]:
df

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,2,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000
5,1006,Isha Trivedi,2,25.0,51000,2023/04/21,Vadodara,Active,Human Resources,Ahmedabad,Neha Patel,6500000
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,Pune,Active,Sales,Pune,Priya Desai,10000000
10,1011,Dev Shah,2,26.0,50000,2022-08-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
11,1012,Sara Khan,6,29.0,58000,2021-10-30,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
14,1015,Riya Mehta,5,24.0,"47,000",2024-03-01,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
15,1016,Neil Desai,4,33.0,80000,2020-09-12,Pune,Active,Sales,Pune,Priya Desai,10000000
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
17,1018,Om Patel,3,26.0,61000,2023-06-07,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,Jaipur,Active,Customer Support,Jaipur,Meena Sharma,6000000
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
20,1021,Tara Desai,5,27.0,67000,2022-07-22,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
24,1025,Kunal Mehta,8,34.0,NaN,2019-11-11,Mumbai,Active,Research and Development,Mumbai,Vikram Rao,11000000
25,1026,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
26,1027,Neha Patel,3,31.0,63000,NaN,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,NaN,Active,Engineering,Surat,Rajesh Shah,12000000
28,1029,Priya Desai,4,30.0,71000,2020-06-21,Pune,Active,Sales,Pune,Priya Desai,10000000
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
30,1031,Meera Shah,2,26.0,53000,2023-05-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
33,1034,Akash Desai,4,36.0,90000,2018-07-20,Pune,Active,Sales,Pune,Priya Desai,10000000
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
35,1036,Karan Shah,6,32.0,61000,2020-10-10,Delhi,Inactive,Operations,Delhi,Sanjay Kumar,7500000
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,Pune,Active,Sales,Pune,Priya Desai,10000000
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
40,1041,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
41,1042,Heena Patel,3,26.0,58000,2022-06-16,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,Pune,Active,Sales,Pune,Priya Desai,10000000
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
46,1047,Hetal Patel,3,27.0,"62,000",2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
49,1050,Devika Shah,2,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [264]:
df.isnull().sum()

employee_id        0
employee_name      0
dept_id            0
age                2
salary             1
joining_date       1
city               1
status             0
department_name    0
location           0
manager            0
annual_budget      0
dtype: int64

In [265]:
df["salary"] = pd.to_numeric(df["salary"],errors="coerce").astype("Int64")
df

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,2,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000
5,1006,Isha Trivedi,2,25.0,51000,2023/04/21,Vadodara,Active,Human Resources,Ahmedabad,Neha Patel,6500000
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,Pune,Active,Sales,Pune,Priya Desai,10000000
10,1011,Dev Shah,2,26.0,50000,2022-08-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
11,1012,Sara Khan,6,29.0,58000,2021-10-30,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
14,1015,Riya Mehta,5,24.0,<NA>,2024-03-01,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
15,1016,Neil Desai,4,33.0,80000,2020-09-12,Pune,Active,Sales,Pune,Priya Desai,10000000
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
17,1018,Om Patel,3,26.0,61000,2023-06-07,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,Jaipur,Active,Customer Support,Jaipur,Meena Sharma,6000000
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
20,1021,Tara Desai,5,27.0,67000,2022-07-22,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
24,1025,Kunal Mehta,8,34.0,<NA>,2019-11-11,Mumbai,Active,Research and Development,Mumbai,Vikram Rao,11000000
25,1026,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
26,1027,Neha Patel,3,31.0,63000,NaN,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,NaN,Active,Engineering,Surat,Rajesh Shah,12000000
28,1029,Priya Desai,4,30.0,71000,2020-06-21,Pune,Active,Sales,Pune,Priya Desai,10000000
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
30,1031,Meera Shah,2,26.0,53000,2023-05-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
33,1034,Akash Desai,4,36.0,90000,2018-07-20,Pune,Active,Sales,Pune,Priya Desai,10000000
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
35,1036,Karan Shah,6,32.0,61000,2020-10-10,Delhi,Inactive,Operations,Delhi,Sanjay Kumar,7500000
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,Pune,Active,Sales,Pune,Priya Desai,10000000
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
40,1041,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
41,1042,Heena Patel,3,26.0,58000,2022-06-16,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,Pune,Active,Sales,Pune,Priya Desai,10000000
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
46,1047,Hetal Patel,3,27.0,<NA>,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
49,1050,Devika Shah,2,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [266]:
df["salary"].describe()

count            44.0
mean     60022.727273
std      12459.214646
min           39000.0
25%           49750.0
50%           60500.0
75%           68250.0
max           90000.0
Name: salary, dtype: Float64

In [267]:
std = 12356.104207

min = (df["salary"].mean()) - 3*std
max = (df["salary"].mean()) + 3*std

df = df[(df["salary"]>=min) & (df["salary"]<=max)]
df

,employee_id,employee_name,dept_id,age,salary,joining_date,city,status,department_name,location,manager,annual_budget
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
1,1002,Diya Patel,2,27.0,52000,15/02/2022,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,Pune,Active,Sales,Pune,Priya Desai,10000000
5,1006,Isha Trivedi,2,25.0,51000,2023/04/21,Vadodara,Active,Human Resources,Ahmedabad,Neha Patel,6500000
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,Pune,Active,Sales,Pune,Priya Desai,10000000
10,1011,Dev Shah,2,26.0,50000,2022-08-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
11,1012,Sara Khan,6,29.0,58000,2021-10-30,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
15,1016,Neil Desai,4,33.0,80000,2020-09-12,Pune,Active,Sales,Pune,Priya Desai,10000000
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
17,1018,Om Patel,3,26.0,61000,2023-06-07,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,Jaipur,Active,Customer Support,Jaipur,Meena Sharma,6000000
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
20,1021,Tara Desai,5,27.0,67000,2022-07-22,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,Bengaluru,Inactive,Marketing,Bengaluru,Karan Joshi,9000000
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
25,1026,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
26,1027,Neha Patel,3,31.0,63000,NaN,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,NaN,Active,Engineering,Surat,Rajesh Shah,12000000
28,1029,Priya Desai,4,30.0,71000,2020-06-21,Pune,Active,Sales,Pune,Priya Desai,10000000
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
30,1031,Meera Shah,2,26.0,53000,2023-05-19,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
33,1034,Akash Desai,4,36.0,90000,2018-07-20,Pune,Active,Sales,Pune,Priya Desai,10000000
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
35,1036,Karan Shah,6,32.0,61000,2020-10-10,Delhi,Inactive,Operations,Delhi,Sanjay Kumar,7500000
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,Pune,Active,Sales,Pune,Priya Desai,10000000
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
40,1041,Rahul Shah,2,NaN,49000,2023-08-14,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000
41,1042,Heena Patel,3,26.0,58000,2022-06-16,Mumbai,Active,Finance,Mumbai,Amit Mehta,8000000
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,Pune,Active,Sales,Pune,Priya Desai,10000000
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,Bengaluru,Active,Marketing,Bengaluru,Karan Joshi,9000000
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,Delhi,Active,Operations,Delhi,Sanjay Kumar,7500000
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,Surat,Active,Engineering,Surat,Rajesh Shah,12000000
49,1050,Devika Shah,2,29.0,57000,2022-02-28,Ahmedabad,Active,Human Resources,Ahmedabad,Neha Patel,6500000

In [268]:
df.isnull().sum()

employee_id        0
employee_name      0
dept_id            0
age                2
salary             0
joining_date       1
city               1
status             0
department_name    0
location           0
manager            0
annual_budget      0
dtype: int64

In [269]:
df["age"] = df["age"].fillna(df["age"].mode()[0])
df["joining_date"].unique()
df["joining_date"] = df["joining_date"].fillna(df["joining_date"].mode()[0])
df["city"] = df["city"].fillna(df["city"].mode()[0])
df = pd.get_dummies(df, columns=["city"], dtype=int)
df = pd.get_dummies(df, columns=["location"], dtype=int)

In [270]:
df

,employee_id,employee_name,dept_id,age,salary,joining_date,status,department_name,manager,annual_budget,...,city_Pune,city_Surat,city_Vadodara,location_Ahmedabad,location_Bengaluru,location_Delhi,location_Jaipur,location_Mumbai,location_Pune,location_Surat
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
1,1002,Diya Patel,2,27.0,52000,15/02/2022,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
5,1006,Isha Trivedi,2,25.0,51000,2023/04/21,Active,Human Resources,Neha Patel,6500000,...,0,0,1,1,0,0,0,0,0,0
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,Inactive,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
10,1011,Dev Shah,2,26.0,50000,2022-08-19,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
11,1012,Sara Khan,6,29.0,58000,2021-10-30,Active,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
15,1016,Neil Desai,4,33.0,80000,2020-09-12,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
17,1018,Om Patel,3,26.0,61000,2023-06-07,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,Active,Customer Support,Meena Sharma,6000000,...,0,0,0,0,0,0,1,0,0,0
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
20,1021,Tara Desai,5,27.0,67000,2022-07-22,Inactive,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,Inactive,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
25,1026,Rahul Shah,2,24.0,49000,2023-08-14,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
26,1027,Neha Patel,3,31.0,63000,2021-09-05,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
28,1029,Priya Desai,4,30.0,71000,2020-06-21,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
30,1031,Meera Shah,2,26.0,53000,2023-05-19,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
33,1034,Akash Desai,4,36.0,90000,2018-07-20,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
35,1036,Karan Shah,6,32.0,61000,2020-10-10,Inactive,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
40,1041,Rahul Shah,2,24.0,49000,2023-08-14,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
41,1042,Heena Patel,3,26.0,58000,2022-06-16,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,Active,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
49,1050,Devika Shah,2,29.0,57000,2022-02-28,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0

In [271]:
df.isnull().sum()

employee_id           0
employee_name         0
dept_id               0
age                   0
salary                0
joining_date          0
status                0
department_name       0
manager               0
annual_budget         0
city_Ahmedabad        0
city_Bengaluru        0
city_Delhi            0
city_Jaipur           0
city_Mumbai           0
city_Pune             0
city_Surat            0
city_Vadodara         0
location_Ahmedabad    0
location_Bengaluru    0
location_Delhi        0
location_Jaipur       0
location_Mumbai       0
location_Pune         0
location_Surat        0
dtype: int64

In [272]:
df.describe()

,employee_id,dept_id,age,salary,city_Ahmedabad,city_Bengaluru,city_Delhi,city_Jaipur,city_Mumbai,city_Pune,city_Surat,city_Vadodara,location_Ahmedabad,location_Bengaluru,location_Delhi,location_Jaipur,location_Mumbai,location_Pune,location_Surat
count,44.000000,44.000000,44.000000,44.0,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000
mean,1024.613636,3.090909,28.022727,60022.727273,0.159091,0.159091,0.068182,0.022727,0.159091,0.159091,0.250000,0.022727,0.181818,0.159091,0.068182,0.022727,0.159091,0.159091,0.250000
std,14.633850,1.736318,3.433682,12459.214646,0.369989,0.369989,0.254972,0.150756,0.369989,0.369989,0.438019,0.150756,0.390154,0.369989,0.254972,0.150756,0.369989,0.369989,0.438019
min,1001.000000,1.000000,22.000000,39000.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1011.750000,1.750000,25.750000,49750.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1024.500000,3.000000,28.000000,60500.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1037.250000,4.250000,30.000000,68250.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000
max,1050.000000,7.000000,36.000000,90000.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [273]:
df.dtypes

employee_id             int64
employee_name             str
dept_id                 int64
age                   float64
salary                  Int64
joining_date              str
status                    str
department_name           str
manager                   str
annual_budget             str
city_Ahmedabad          int64
city_Bengaluru          int64
city_Delhi              int64
city_Jaipur             int64
city_Mumbai             int64
city_Pune               int64
city_Surat              int64
city_Vadodara           int64
location_Ahmedabad      int64
location_Bengaluru      int64
location_Delhi          int64
location_Jaipur         int64
location_Mumbai         int64
location_Pune           int64
location_Surat          int64
dtype: object

In [274]:
df["joining_date"] = pd.to_datetime(
    df["joining_date"],
    errors="coerce"
)
df

,employee_id,employee_name,dept_id,age,salary,joining_date,status,department_name,manager,annual_budget,...,city_Pune,city_Surat,city_Vadodara,location_Ahmedabad,location_Bengaluru,location_Delhi,location_Jaipur,location_Mumbai,location_Pune,location_Surat
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
1,1002,Diya Patel,2,27.0,52000,NaT,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
5,1006,Isha Trivedi,2,25.0,51000,NaT,Active,Human Resources,Neha Patel,6500000,...,0,0,1,1,0,0,0,0,0,0
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,Inactive,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
10,1011,Dev Shah,2,26.0,50000,2022-08-19,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
11,1012,Sara Khan,6,29.0,58000,2021-10-30,Active,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
15,1016,Neil Desai,4,33.0,80000,2020-09-12,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
17,1018,Om Patel,3,26.0,61000,2023-06-07,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,Active,Customer Support,Meena Sharma,6000000,...,0,0,0,0,0,0,1,0,0,0
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
20,1021,Tara Desai,5,27.0,67000,2022-07-22,Inactive,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,Inactive,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
25,1026,Rahul Shah,2,24.0,49000,2023-08-14,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
26,1027,Neha Patel,3,31.0,63000,2021-09-05,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
28,1029,Priya Desai,4,30.0,71000,2020-06-21,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
30,1031,Meera Shah,2,26.0,53000,2023-05-19,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
33,1034,Akash Desai,4,36.0,90000,2018-07-20,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
35,1036,Karan Shah,6,32.0,61000,2020-10-10,Inactive,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
40,1041,Rahul Shah,2,24.0,49000,2023-08-14,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
41,1042,Heena Patel,3,26.0,58000,2022-06-16,Active,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,Active,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,Active,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,Active,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,Active,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
49,1050,Devika Shah,2,29.0,57000,2022-02-28,Active,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
df["status"].unique()
df["status"] = df["status"].map({
    "Active": 1,
    "Inactive": 0
})

In [276]:
df["annual_budget"] = pd.to_numeric(
    df["annual_budget"],
    errors="coerce"
).astype("Int64")

In [277]:
df

,employee_id,employee_name,dept_id,age,salary,joining_date,status,department_name,manager,annual_budget,...,city_Pune,city_Surat,city_Vadodara,location_Ahmedabad,location_Bengaluru,location_Delhi,location_Jaipur,location_Mumbai,location_Pune,location_Surat
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
1,1002,Diya Patel,2,27.0,52000,NaT,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
5,1006,Isha Trivedi,2,25.0,51000,NaT,1,Human Resources,Neha Patel,6500000,...,0,0,1,1,0,0,0,0,0,0
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
10,1011,Dev Shah,2,26.0,50000,2022-08-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
11,1012,Sara Khan,6,29.0,58000,2021-10-30,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
15,1016,Neil Desai,4,33.0,80000,2020-09-12,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
17,1018,Om Patel,3,26.0,61000,2023-06-07,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,1,Customer Support,Meena Sharma,6000000,...,0,0,0,0,0,0,1,0,0,0
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
20,1021,Tara Desai,5,27.0,67000,2022-07-22,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
25,1026,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
26,1027,Neha Patel,3,31.0,63000,2021-09-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
28,1029,Priya Desai,4,30.0,71000,2020-06-21,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
30,1031,Meera Shah,2,26.0,53000,2023-05-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
33,1034,Akash Desai,4,36.0,90000,2018-07-20,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
35,1036,Karan Shah,6,32.0,61000,2020-10-10,0,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
40,1041,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
41,1042,Heena Patel,3,26.0,58000,2022-06-16,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
49,1050,Devika Shah,2,29.0,57000,2022-02-28,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0

In [278]:
df.dtypes

employee_id                    int64
employee_name                    str
dept_id                        int64
age                          float64
salary                         Int64
joining_date          datetime64[us]
status                         int64
department_name                  str
manager                          str
annual_budget                  Int64
city_Ahmedabad                 int64
city_Bengaluru                 int64
city_Delhi                     int64
city_Jaipur                    int64
city_Mumbai                    int64
city_Pune                      int64
city_Surat                     int64
city_Vadodara                  int64
location_Ahmedabad             int64
location_Bengaluru             int64
location_Delhi                 int64
location_Jaipur                int64
location_Mumbai                int64
location_Pune                  int64
location_Surat                 int64
dtype: object

In [279]:
df["manager"] = df["manager"].fillna(df["manager"].mode()[0])

In [280]:
df["department_name"] = df["department_name"].fillna(
    df["department_name"].mode()[0]
)

In [281]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
25    False
26    False
27    False
28    False
29    False
30    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
47    False
49    False
dtype: bool

In [282]:
df

,employee_id,employee_name,dept_id,age,salary,joining_date,status,department_name,manager,annual_budget,...,city_Pune,city_Surat,city_Vadodara,location_Ahmedabad,location_Bengaluru,location_Delhi,location_Jaipur,location_Mumbai,location_Pune,location_Surat
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
1,1002,Diya Patel,2,27.0,52000,NaT,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
5,1006,Isha Trivedi,2,25.0,51000,NaT,1,Human Resources,Neha Patel,6500000,...,0,0,1,1,0,0,0,0,0,0
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
10,1011,Dev Shah,2,26.0,50000,2022-08-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
11,1012,Sara Khan,6,29.0,58000,2021-10-30,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
15,1016,Neil Desai,4,33.0,80000,2020-09-12,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
17,1018,Om Patel,3,26.0,61000,2023-06-07,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,1,Customer Support,Meena Sharma,6000000,...,0,0,0,0,0,0,1,0,0,0
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
20,1021,Tara Desai,5,27.0,67000,2022-07-22,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
25,1026,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
26,1027,Neha Patel,3,31.0,63000,2021-09-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
28,1029,Priya Desai,4,30.0,71000,2020-06-21,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
30,1031,Meera Shah,2,26.0,53000,2023-05-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
33,1034,Akash Desai,4,36.0,90000,2018-07-20,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
35,1036,Karan Shah,6,32.0,61000,2020-10-10,0,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
40,1041,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
41,1042,Heena Patel,3,26.0,58000,2022-06-16,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
49,1050,Devika Shah,2,29.0,57000,2022-02-28,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0

In [283]:
df.dtypes

employee_id                    int64
employee_name                    str
dept_id                        int64
age                          float64
salary                         Int64
joining_date          datetime64[us]
status                         int64
department_name                  str
manager                          str
annual_budget                  Int64
city_Ahmedabad                 int64
city_Bengaluru                 int64
city_Delhi                     int64
city_Jaipur                    int64
city_Mumbai                    int64
city_Pune                      int64
city_Surat                     int64
city_Vadodara                  int64
location_Ahmedabad             int64
location_Bengaluru             int64
location_Delhi                 int64
location_Jaipur                int64
location_Mumbai                int64
location_Pune                  int64
location_Surat                 int64
dtype: object

In [284]:
df["joining_date"].unique()

<DatetimeArray>
['2023-01-15 00:00:00',                 'NaT', '2021-07-10 00:00:00',
 '2022-11-01 00:00:00', '2020-03-18 00:00:00', '2021-09-05 00:00:00',
 '2020-12-11 00:00:00', '2024-01-08 00:00:00', '2019-06-25 00:00:00',
 '2022-08-19 00:00:00', '2021-10-30 00:00:00', '2023-02-14 00:00:00',
 '2018-05-17 00:00:00', '2020-09-12 00:00:00', '2022-01-20 00:00:00',
 '2023-06-07 00:00:00', '2021-04-16 00:00:00', '2024-05-10 00:00:00',
 '2022-07-22 00:00:00', '2023-08-14 00:00:00', '2024-02-18 00:00:00',
 '2020-06-21 00:00:00', '2022-03-11 00:00:00', '2023-05-19 00:00:00',
 '2022-09-15 00:00:00', '2018-07-20 00:00:00', '2024-01-25 00:00:00',
 '2020-10-10 00:00:00', '2023-03-05 00:00:00', '2019-04-17 00:00:00',
 '2021-08-09 00:00:00', '2020-01-13 00:00:00', '2022-06-16 00:00:00',
 '2024-04-12 00:00:00', '2022-11-30 00:00:00', '2021-05-18 00:00:00',
 '2019-09-23 00:00:00', '2022-02-28 00:00:00']
Length: 38, dtype: datetime64[us]

In [285]:
df

,employee_id,employee_name,dept_id,age,salary,joining_date,status,department_name,manager,annual_budget,...,city_Pune,city_Surat,city_Vadodara,location_Ahmedabad,location_Bengaluru,location_Delhi,location_Jaipur,location_Mumbai,location_Pune,location_Surat
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
1,1002,Diya Patel,2,27.0,52000,NaT,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
5,1006,Isha Trivedi,2,25.0,51000,NaT,1,Human Resources,Neha Patel,6500000,...,0,0,1,1,0,0,0,0,0,0
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
10,1011,Dev Shah,2,26.0,50000,2022-08-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
11,1012,Sara Khan,6,29.0,58000,2021-10-30,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
15,1016,Neil Desai,4,33.0,80000,2020-09-12,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
17,1018,Om Patel,3,26.0,61000,2023-06-07,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,1,Customer Support,Meena Sharma,6000000,...,0,0,0,0,0,0,1,0,0,0
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
20,1021,Tara Desai,5,27.0,67000,2022-07-22,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
25,1026,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
26,1027,Neha Patel,3,31.0,63000,2021-09-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
28,1029,Priya Desai,4,30.0,71000,2020-06-21,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
30,1031,Meera Shah,2,26.0,53000,2023-05-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
33,1034,Akash Desai,4,36.0,90000,2018-07-20,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
35,1036,Karan Shah,6,32.0,61000,2020-10-10,0,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
40,1041,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
41,1042,Heena Patel,3,26.0,58000,2022-06-16,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
49,1050,Devika Shah,2,29.0,57000,2022-02-28,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0

In [286]:
df.isnull().sum()

employee_id           0
employee_name         0
dept_id               0
age                   0
salary                0
joining_date          2
status                0
department_name       0
manager               0
annual_budget         0
city_Ahmedabad        0
city_Bengaluru        0
city_Delhi            0
city_Jaipur           0
city_Mumbai           0
city_Pune             0
city_Surat            0
city_Vadodara         0
location_Ahmedabad    0
location_Bengaluru    0
location_Delhi        0
location_Jaipur       0
location_Mumbai       0
location_Pune         0
location_Surat        0
dtype: int64

In [287]:
df["joining_date"] = df["joining_date"].fillna(
    df["joining_date"].mode()[0]
)

In [288]:
df

,employee_id,employee_name,dept_id,age,salary,joining_date,status,department_name,manager,annual_budget,...,city_Pune,city_Surat,city_Vadodara,location_Ahmedabad,location_Bengaluru,location_Delhi,location_Jaipur,location_Mumbai,location_Pune,location_Surat
0,1001,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
1,1002,Diya Patel,2,27.0,52000,2021-09-05,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,3,29.0,60000,2021-07-10,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
3,1004,Mira Joshi,1,26.0,48000,2022-11-01,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
4,1005,Kabir Desai,4,31.0,72000,2020-03-18,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
5,1006,Isha Trivedi,2,25.0,51000,2021-09-05,1,Human Resources,Neha Patel,6500000,...,0,0,1,1,0,0,0,0,0,0
6,1007,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
7,1008,Anaya Mehta,3,30.0,68000,2020-12-11,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
8,1009,Arjun Patel,1,23.0,42000,2024-01-08,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
9,1010,Kiara Desai,4,32.0,75000,2019-06-25,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
10,1011,Dev Shah,2,26.0,50000,2022-08-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
11,1012,Sara Khan,6,29.0,58000,2021-10-30,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
12,1013,Yashvi Patel,3,27.0,62000,2023-02-14,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
13,1014,Manav Joshi,1,35.0,85000,2018-05-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
15,1016,Neil Desai,4,33.0,80000,2020-09-12,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
16,1017,Aditi Shah,2,28.0,54000,2022-01-20,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
17,1018,Om Patel,3,26.0,61000,2023-06-07,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
18,1019,Nisha Joshi,7,30.0,59000,2021-04-16,1,Customer Support,Meena Sharma,6000000,...,0,0,0,0,0,0,1,0,0,0
19,1020,Reyansh Mehta,1,22.0,39000,2024-05-10,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
20,1021,Tara Desai,5,27.0,67000,2022-07-22,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
21,1022,Vivaan Shah,5,28.0,65000,2021-09-05,0,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
22,1023,Aarav Shah,1,24.0,45000,2023-01-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
25,1026,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
26,1027,Neha Patel,3,31.0,63000,2021-09-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
27,1028,Jay Joshi,1,25.0,44000,2024-02-18,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
28,1029,Priya Desai,4,30.0,71000,2020-06-21,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
29,1030,Harsh Mehta,5,27.0,66000,2022-03-11,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
30,1031,Meera Shah,2,26.0,53000,2023-05-19,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
32,1033,Simran Joshi,1,28.0,55000,2022-09-15,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
33,1034,Akash Desai,4,36.0,90000,2018-07-20,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
34,1035,Divya Mehta,5,24.0,48000,2024-01-25,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
35,1036,Karan Shah,6,32.0,61000,2020-10-10,0,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
36,1037,Anjali Patel,3,27.0,62000,2023-03-05,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
37,1038,Mohit Joshi,1,33.0,78000,2019-04-17,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
38,1039,Sneha Desai,4,29.0,69000,2021-08-09,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
39,1040,Varun Mehta,5,31.0,73000,2020-01-13,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
40,1041,Rahul Shah,2,24.0,49000,2023-08-14,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0
41,1042,Heena Patel,3,26.0,58000,2022-06-16,1,Finance,Amit Mehta,8000000,...,0,0,0,0,0,0,0,1,0,0
42,1043,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
43,1044,Nidhi Desai,4,28.0,64000,2022-11-30,1,Sales,Priya Desai,10000000,...,1,0,0,0,0,0,0,0,1,0
44,1045,Krish Mehta,5,30.0,70000,2021-05-18,1,Marketing,Karan Joshi,9000000,...,0,0,0,0,1,0,0,0,0,0
45,1046,Maulik Shah,6,35.0,76000,2019-09-23,1,Operations,Sanjay Kumar,7500000,...,0,0,0,0,0,1,0,0,0,0
47,1048,Parth Joshi,1,24.0,41000,2024-04-12,1,Engineering,Rajesh Shah,12000000,...,0,1,0,0,0,0,0,0,0,1
49,1050,Devika Shah,2,29.0,57000,2022-02-28,1,Human Resources,Neha Patel,6500000,...,0,0,0,1,0,0,0,0,0,0

In [289]:
df.shape

(44, 25)

In [290]:
df.duplicated().sum()

np.int64(0)

In [291]:
df.isnull().sum()

employee_id           0
employee_name         0
dept_id               0
age                   0
salary                0
joining_date          0
status                0
department_name       0
manager               0
annual_budget         0
city_Ahmedabad        0
city_Bengaluru        0
city_Delhi            0
city_Jaipur           0
city_Mumbai           0
city_Pune             0
city_Surat            0
city_Vadodara         0
location_Ahmedabad    0
location_Bengaluru    0
location_Delhi        0
location_Jaipur       0
location_Mumbai       0
location_Pune         0
location_Surat        0
dtype: int64

In [296]:
df[df["salary"] > 60000][["employee_name","salary"]]

   employee_name  salary
4    Kabir Desai   72000
6    Vivaan Shah   65000
7    Anaya Mehta   68000
9    Kiara Desai   75000
12  Yashvi Patel   62000
13   Manav Joshi   85000
15    Neil Desai   80000
17      Om Patel   61000
20    Tara Desai   67000
21   Vivaan Shah   65000
26    Neha Patel   63000
28   Priya Desai   71000
29   Harsh Mehta   66000
33   Akash Desai   90000
35    Karan Shah   61000
36  Anjali Patel   62000
37   Mohit Joshi   78000
38   Sneha Desai   69000
39   Varun Mehta   73000
43   Nidhi Desai   64000
44   Krish Mehta   70000
45   Maulik Shah   76000

In [299]:
df[df["age"] > 30][["employee_name","age"]]

   employee_name   age
4    Kabir Desai  31.0
9    Kiara Desai  32.0
13   Manav Joshi  35.0
15    Neil Desai  33.0
26    Neha Patel  31.0
33   Akash Desai  36.0
35    Karan Shah  32.0
37   Mohit Joshi  33.0
39   Varun Mehta  31.0
45   Maulik Shah  35.0

In [300]:
df[df["department_name"] == "Engineering"][["employee_name","department_name"]]

     employee_name department_name
0       Aarav Shah     Engineering
3       Mira Joshi     Engineering
8      Arjun Patel     Engineering
13     Manav Joshi     Engineering
19   Reyansh Mehta     Engineering
22      Aarav Shah     Engineering
27       Jay Joshi     Engineering
32    Simran Joshi     Engineering
37     Mohit Joshi     Engineering
42     Parth Joshi     Engineering
47     Parth Joshi     Engineering

In [301]:
df[df["status"] == 1][["employee_name","department_name"]]

       employee_name   department_name
0         Aarav Shah       Engineering
1         Diya Patel   Human Resources
2        Rohan Mehta           Finance
3         Mira Joshi       Engineering
4        Kabir Desai             Sales
5       Isha Trivedi   Human Resources
7        Anaya Mehta           Finance
8        Arjun Patel       Engineering
9        Kiara Desai             Sales
10          Dev Shah   Human Resources
11         Sara Khan        Operations
12      Yashvi Patel           Finance
13       Manav Joshi       Engineering
15        Neil Desai             Sales
16        Aditi Shah   Human Resources
17          Om Patel           Finance
18       Nisha Joshi  Customer Support
19     Reyansh Mehta       Engineering
22        Aarav Shah       Engineering
25        Rahul Shah   Human Resources
26        Neha Patel           Finance
27         Jay Joshi       Engineering
28       Priya Desai             Sales
29       Harsh Mehta         Marketing
30     Meera Shah      Human Resources
32      Simran Joshi       Engineering
33       Akash Desai             Sales
34       Divya Mehta         Marketing
36      Anjali Patel           Finance
37       Mohit Joshi       Engineering
38       Sneha Desai             Sales
39       Varun Mehta         Marketing
40        Rahul Shah   Human Resources
41       Heena Patel           Finance
42       Parth Joshi       Engineering
43       Nidhi Desai             Sales
44       Krish Mehta         Marketing
45       Maulik Shah        Operations
47       Parth Joshi       Engineering
49       Devika Shah   Human Resources

In [302]:
df[(df["salary"]>60000) & (df["status"] == 1)][["employee_name","department_name"]]

   employee_name department_name
4    Kabir Desai           Sales
7    Anaya Mehta         Finance
9    Kiara Desai           Sales
12  Yashvi Patel         Finance
13   Manav Joshi     Engineering
15    Neil Desai           Sales
17      Om Patel         Finance
26    Neha Patel         Finance
28   Priya Desai           Sales
29   Harsh Mehta       Marketing
33   Akash Desai           Sales
36  Anjali Patel         Finance
37   Mohit Joshi     Engineering
38   Sneha Desai           Sales
39   Varun Mehta       Marketing
43   Nidhi Desai           Sales
44   Krish Mehta       Marketing
45   Maulik Shah      Operations

In [303]:
df[(df["department_name"] == "Engineering") & (df["salary"]>60000)][["employee_name","department_name"]]

   employee_name department_name
13   Manav Joshi     Engineering
37   Mohit Joshi     Engineering

In [304]:
df[(df["department_name"] == "Engineering") | (df["salary"]>60000)][["employee_name","department_name"]]

     employee_name department_name
0       Aarav Shah     Engineering
3       Mira Joshi     Engineering
4      Kabir Desai           Sales
6      Vivaan Shah       Marketing
7      Anaya Mehta         Finance
8      Arjun Patel     Engineering
9      Kiara Desai           Sales
12    Yashvi Patel         Finance
13     Manav Joshi     Engineering
15      Neil Desai           Sales
17        Om Patel         Finance
19   Reyansh Mehta     Engineering
20      Tara Desai       Marketing
21     Vivaan Shah       Marketing
22      Aarav Shah     Engineering
26      Neha Patel         Finance
27       Jay Joshi     Engineering
28     Priya Desai           Sales
29     Harsh Mehta       Marketing
32    Simran Joshi     Engineering
33     Akash Desai           Sales
35      Karan Shah      Operations
36    Anjali Patel         Finance
37     Mohit Joshi     Engineering
38     Sneha Desai           Sales
39     Varun Mehta       Marketing
42     Parth Joshi     Engineering
43     Nidhi Desai           Sales
44     Krish Mehta       Marketing
45     Maulik Shah      Operations
47     Parth Joshi     Engineering

In [306]:
df[(df["salary"]>50000) & (df["salary"]<80000)][["employee_name","department_name","salary"]]

       employee_name   department_name  salary
1         Diya Patel   Human Resources   52000
2        Rohan Mehta           Finance   60000
4        Kabir Desai             Sales   72000
5       Isha Trivedi   Human Resources   51000
6        Vivaan Shah         Marketing   65000
7        Anaya Mehta           Finance   68000
9        Kiara Desai             Sales   75000
11         Sara Khan        Operations   58000
12      Yashvi Patel           Finance   62000
16        Aditi Shah   Human Resources   54000
17          Om Patel           Finance   61000
18       Nisha Joshi  Customer Support   59000
20        Tara Desai         Marketing   67000
21       Vivaan Shah         Marketing   65000
26        Neha Patel           Finance   63000
28       Priya Desai             Sales   71000
29       Harsh Mehta         Marketing   66000
30     Meera Shah      Human Resources   53000
32      Simran Joshi       Engineering   55000
35        Karan Shah        Operations   61000
36      Anjali Patel           Finance   62000
37       Mohit Joshi       Engineering   78000
38       Sneha Desai             Sales   69000
39       Varun Mehta         Marketing   73000
41       Heena Patel           Finance   58000
43       Nidhi Desai             Sales   64000
44       Krish Mehta         Marketing   70000
45       Maulik Shah        Operations   76000
49       Devika Shah   Human Resources   57000

In [307]:
df.sort_values("salary", ascending=False)[["employee_name", "salary"]].head(5)

   employee_name  salary
33   Akash Desai   90000
13   Manav Joshi   85000
15    Neil Desai   80000
37   Mohit Joshi   78000
45   Maulik Shah   76000

In [310]:
employee_count = df.groupby("department_name").size()

print(employee_count)

department_name
Customer Support     1
Engineering         11
Finance              7
Human Resources      8
Marketing            7
Operations           3
Sales                7
dtype: int64

In [315]:
a = df.groupby("department_name")["salary"].mean()
print(a)

department_name
Customer Support         59000.0
Engineering         51181.818182
Finance                  62000.0
Human Resources          51875.0
Marketing           64857.142857
Operations               65000.0
Sales               74428.571429
Name: salary, dtype: Float64

In [318]:
a = df.groupby("department_name")["salary"].sum()
print(a)

department_name
Customer Support     59000
Engineering         563000
Finance             434000
Human Resources     415000
Marketing           454000
Operations          195000
Sales               521000
Name: salary, dtype: Int64

In [319]:
a = df.groupby("department_name")["salary"].agg([
    "count",
    "mean",
    "sum"
])

print(a)

                  count          mean     sum
department_name
Customer Support      1       59000.0   59000
Engineering          11  51181.818182  563000
Finance               7       62000.0  434000
Human Resources       8       51875.0  415000
Marketing             7  64857.142857  454000
Operations            3       65000.0  195000
Sales                 7  74428.571429  521000

In [321]:
a = df.groupby(["department_name", "status"]).size()

print(a)

department_name   status
Customer Support  1          1
Engineering       1         11
Finance           1          7
Human Resources   1          8
Marketing         0          3
                  1          4
Operations        0          1
                  1          2
Sales             1          7
dtype: int64

In [323]:
df.groupby("manager").agg(
    employee_count=("employee_id", "count"),
    average_salary=("salary", "mean")
)

              employee_count  average_salary
manager
Amit Mehta                 7         62000.0
Karan Joshi                7    64857.142857
Meena Sharma               1         59000.0
Neha Patel                 8         51875.0
Priya Desai                7    74428.571429
Rajesh Shah               11    51181.818182
Sanjay Kumar               3         65000.0

In [326]:
print(df.isnull().sum())

employee_id           0
employee_name         0
dept_id               0
age                   0
salary                0
joining_date          0
status                0
department_name       0
manager               0
annual_budget         0
city_Ahmedabad        0
city_Bengaluru        0
city_Delhi            0
city_Jaipur           0
city_Mumbai           0
city_Pune             0
city_Surat            0
city_Vadodara         0
location_Ahmedabad    0
location_Bengaluru    0
location_Delhi        0
location_Jaipur       0
location_Mumbai       0
location_Pune         0
location_Surat        0
dtype: int64

In [325]:
print(df.shape)

(44, 25)

In [327]:
print(df.duplicated().sum())

0

In [328]:
print(df["status"].unique())

[1 0]

In [329]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Null values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Rows: 44
Columns: 25
Null values: 0
Duplicate rows: 0

In [330]:
print(df["employee_id"].duplicated().sum())

0

In [331]:
df.to_csv("final_employee_report.csv", index=False)