In [212]:
import pandas as pd

df = pd.read_csv("Dataset.csv")

df

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience_Years,Salary,Joining_Year,Performance_Score,City,Education,Remote,Overtime_Hours,Leave_Days
0,1001,Aarav Shah,23.0,Male,IT,Developer,1.0,28000.0,2024,7.5,Surat,BSc IT,Yes,5.0,8.0
1,1002,Diya Patel,25.0,Female,HR,HR Executive,2.0,32000.0,2023,8.1,Ahmedabad,MBA,No,2.0,6.0
2,1003,Rohan Mehta,NaN,Male,Finance,Accountant,5.0,55000.0,2020,6.8,Vadodara,BCom,Yes,8.0,12.0
3,1004,Kavya Desai,31.0,Female,IT,Data Analyst,7.0,NaN,2018,9.0,Surat,BSc IT,Yes,10.0,5.0
4,1005,Arjun Joshi,27.0,Male,Sales,NaN,4.0,45000.0,2021,7.2,Mumbai,BBA,No,4.0,NaN
5,1006,Mira Shah,24.0,Female,HR,Recruiter,2.0,35000.0,2023,NaN,Surat,MBA,Yes,3.0,7.0
6,1007,Dev Patel,35.0,Male,NaN,Senior Developer,10.0,95000.0,2015,9.4,Ahmedabad,MCA,Yes,12.0,4.0
7,1008,Isha Mehta,28.0,Female,Finance,Financial Analyst,NaN,70000.0,2019,7.8,Pune,MCom,No,6.0,9.0
8,1009,Yash Desai,26.0,Male,Sales,Sales Executive,3.0,42000.0,2022,6.9,NaN,BBA,No,7.0,11.0
9,1010,Neha Joshi,30.0,Female,IT,Tester,7.0,65000.0,2018,8.8,Mumbai,BSc IT,NaN,9.0,6.0
10,1011,Raj Shah,33.0,Male,Finance,Accountant,9.0,NaN,2017,7.1,Vadodara,BCom,No,5.0,13.0
11,1012,Anaya Patel,22.0,Female,HR,HR Executive,1.0,30000.0,2025,8.0,Surat,MBA,Yes,1.0,5.0
12,1013,Kunal Mehta,41.0,Male,NaN,Project Manager,15.0,120000.0,2010,9.2,Bangalore,MCA,Yes,15.0,3.0
13,1014,Riya Desai,29.0,Female,Sales,Sales Manager,6.0,78000.0,2019,NaN,Ahmedabad,MBA,No,8.0,8.0
14,1015,Vivan Joshi,37.0,Male,Finance,Financial Analyst,11.0,90000.0,2014,7.9,Pune,MCom,Yes,10.0,7.0
15,1016,Pooja Shah,26.0,Female,IT,Developer,4.0,50000.0,2021,7.4,Surat,BSc IT,Yes,6.0,10.0
16,1017,Manav Patel,32.0,Male,HR,Recruiter,8.0,68000.0,2017,8.7,Mumbai,NaN,No,4.0,6.0
17,1018,Kiara Mehta,28.0,Female,Sales,Sales Executive,5.0,48000.0,2020,6.5,Vadodara,BBA,No,7.0,12.0
18,1019,Dhruv Desai,24.0,Male,IT,Tester,2.0,38000.0,2024,7.0,Surat,BSc IT,Yes,NaN,9.0
19,1020,Nisha Joshi,39.0,Female,Finance,Accountant,13.0,105000.0,2012,9.1,Ahmedabad,BCom,No,11.0,4.0
20,1005,Arjun Joshi,27.0,Male,Sales,NaN,4.0,45000.0,2021,7.2,Mumbai,BBA,No,4.0,NaN
21,1022,Diya Patel,25.0,Female,HR,HR Executive,2.0,32000.0,2023,8.1,Ahmedabad,MBA,No,2.0,6.0
22,1023,Rohan Mehta,29.0,Male,Finance,Accountant,5.0,55000.0,2020,6.8,Vadodara,BCom,Yes,8.0,12.0
23,1024,Kavya Desai,31.0,Female,IT,Data Analyst,7.0,62000.0,2018,9.0,Surat,BSc IT,Yes,10.0,5.0
24,1025,Arjun Joshi,27.0,Male,Sales,Sales Executive,4.0,45000.0,2021,7.2,Mumbai,BBA,No,4.0,10.0

In [213]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience_Years,Salary,Joining_Year,Performance_Score,City,Education,Remote,Overtime_Hours,Leave_Days
0,1001,Aarav Shah,23.0,Male,IT,Developer,1.0,28000.0,2024,7.5,Surat,BSc IT,Yes,5.0,8.0
1,1002,Diya Patel,25.0,Female,HR,HR Executive,2.0,32000.0,2023,8.1,Ahmedabad,MBA,No,2.0,6.0
2,1003,Rohan Mehta,NaN,Male,Finance,Accountant,5.0,55000.0,2020,6.8,Vadodara,BCom,Yes,8.0,12.0
3,1004,Kavya Desai,31.0,Female,IT,Data Analyst,7.0,NaN,2018,9.0,Surat,BSc IT,Yes,10.0,5.0
4,1005,Arjun Joshi,27.0,Male,Sales,NaN,4.0,45000.0,2021,7.2,Mumbai,BBA,No,4.0,NaN

In [214]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        25 non-null     int64
 1   Name               25 non-null     str
 2   Age                24 non-null     float64
 3   Gender             25 non-null     str
 4   Department         23 non-null     str
 5   Job_Role           23 non-null     str
 6   Experience_Years   24 non-null     float64
 7   Salary             23 non-null     float64
 8   Joining_Year       25 non-null     int64
 9   Performance_Score  23 non-null     float64
 10  City               24 non-null     str
 11  Education          24 non-null     str
 12  Remote             24 non-null     str
 13  Overtime_Hours     24 non-null     float64
 14  Leave_Days         23 non-null     float64
dtypes: float64(6), int64(2), str(7)
memory usage: 4.1 KB

Describe

it will give numraic valus colume only means colume type must be int that why it will show this two column only.

In [215]:
df.describe()

,Employee_ID,Age,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days
count,25.000000,24.00000,24.000000,23.000000,25.000000,23.000000,24.000000,23.000000
mean,1012.360000,29.12500,5.708333,57956.521739,2019.400000,7.856522,6.708333,7.739130
std,7.330757,5.00706,3.770355,25284.702995,3.763863,0.904949,3.519871,2.957539
min,1001.000000,22.00000,1.000000,28000.000000,2010.000000,6.500000,1.000000,3.000000
25%,1006.000000,25.75000,2.750000,40000.000000,2018.000000,7.150000,4.000000,5.500000
50%,1012.000000,28.00000,5.000000,50000.000000,2020.000000,7.800000,6.500000,7.000000
75%,1018.000000,31.25000,7.250000,69000.000000,2022.000000,8.750000,9.250000,10.000000
max,1025.000000,41.00000,15.000000,120000.000000,2025.000000,9.400000,15.000000,13.000000

In [216]:
df.shape

(25, 15)

In [217]:
df.describe(include="all")

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience_Years,Salary,Joining_Year,Performance_Score,City,Education,Remote,Overtime_Hours,Leave_Days
count,25.000000,25,24.00000,25,23,23,24.000000,23.000000,25.000000,23.000000,24,24,24,24.000000,23.000000
unique,NaN,20,NaN,2,4,11,NaN,NaN,NaN,NaN,6,6,2,NaN,NaN
top,NaN,Arjun Joshi,NaN,Male,IT,Accountant,NaN,NaN,NaN,NaN,Surat,BSc IT,Yes,NaN,NaN
freq,NaN,3,NaN,13,6,4,NaN,NaN,NaN,NaN,7,6,12,NaN,NaN
mean,1012.360000,NaN,29.12500,NaN,NaN,NaN,5.708333,57956.521739,2019.400000,7.856522,NaN,NaN,NaN,6.708333,7.739130
std,7.330757,NaN,5.00706,NaN,NaN,NaN,3.770355,25284.702995,3.763863,0.904949,NaN,NaN,NaN,3.519871,2.957539
min,1001.000000,NaN,22.00000,NaN,NaN,NaN,1.000000,28000.000000,2010.000000,6.500000,NaN,NaN,NaN,1.000000,3.000000
25%,1006.000000,NaN,25.75000,NaN,NaN,NaN,2.750000,40000.000000,2018.000000,7.150000,NaN,NaN,NaN,4.000000,5.500000
50%,1012.000000,NaN,28.00000,NaN,NaN,NaN,5.000000,50000.000000,2020.000000,7.800000,NaN,NaN,NaN,6.500000,7.000000
75%,1018.000000,NaN,31.25000,NaN,NaN,NaN,7.250000,69000.000000,2022.000000,8.750000,NaN,NaN,NaN,9.250000,10.000000
max,1025.000000,NaN,41.00000,NaN,NaN,NaN,15.000000,120000.000000,2025.000000,9.400000,NaN,NaN,NaN,15.000000,13.000000

In [218]:
df.isnull()

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience_Years,Salary,Joining_Year,Performance_Score,City,Education,Remote,Overtime_Hours,Leave_Days
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
10,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [219]:
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
Gender               0
Department           2
Job_Role             2
Experience_Years     1
Salary               2
Joining_Year         0
Performance_Score    2
City                 1
Education            1
Remote               1
Overtime_Hours       1
Leave_Days           2
dtype: int64

In [220]:
df.isnull().mean()

Employee_ID          0.00
Name                 0.00
Age                  0.04
Gender               0.00
Department           0.08
Job_Role             0.08
Experience_Years     0.04
Salary               0.08
Joining_Year         0.00
Performance_Score    0.08
City                 0.04
Education            0.04
Remote               0.04
Overtime_Hours       0.04
Leave_Days           0.08
dtype: float64

In [221]:
df.isnull().mean()*100

Employee_ID          0.0
Name                 0.0
Age                  4.0
Gender               0.0
Department           8.0
Job_Role             8.0
Experience_Years     4.0
Salary               8.0
Joining_Year         0.0
Performance_Score    8.0
City                 4.0
Education            4.0
Remote               4.0
Overtime_Hours       4.0
Leave_Days           8.0
dtype: float64

In [222]:
age = df["Age"]
print(age)

0     23.0
1     25.0
2      NaN
3     31.0
4     27.0
5     24.0
6     35.0
7     28.0
8     26.0
9     30.0
10    33.0
11    22.0
12    41.0
13    29.0
14    37.0
15    26.0
16    32.0
17    28.0
18    24.0
19    39.0
20    27.0
21    25.0
22    29.0
23    31.0
24    27.0
Name: Age, dtype: float64

In [223]:
a = df[["Age","City","Name"]]
print(a)

     Age       City         Name
0   23.0      Surat   Aarav Shah
1   25.0  Ahmedabad   Diya Patel
2    NaN   Vadodara  Rohan Mehta
3   31.0      Surat  Kavya Desai
4   27.0     Mumbai  Arjun Joshi
5   24.0      Surat    Mira Shah
6   35.0  Ahmedabad    Dev Patel
7   28.0       Pune   Isha Mehta
8   26.0        NaN   Yash Desai
9   30.0     Mumbai   Neha Joshi
10  33.0   Vadodara     Raj Shah
11  22.0      Surat  Anaya Patel
12  41.0  Bangalore  Kunal Mehta
13  29.0  Ahmedabad   Riya Desai
14  37.0       Pune  Vivan Joshi
15  26.0      Surat   Pooja Shah
16  32.0     Mumbai  Manav Patel
17  28.0   Vadodara  Kiara Mehta
18  24.0      Surat  Dhruv Desai
19  39.0  Ahmedabad  Nisha Joshi
20  27.0     Mumbai  Arjun Joshi
21  25.0  Ahmedabad   Diya Patel
22  29.0   Vadodara  Rohan Mehta
23  31.0      Surat  Kavya Desai
24  27.0     Mumbai  Arjun Joshi

In [224]:
filter_row = df[df["Age"] > 20]
print(filter_row[["Name","Gender","City"]])

           Name  Gender       City
0    Aarav Shah    Male      Surat
1    Diya Patel  Female  Ahmedabad
3   Kavya Desai  Female      Surat
4   Arjun Joshi    Male     Mumbai
5     Mira Shah  Female      Surat
6     Dev Patel    Male  Ahmedabad
7    Isha Mehta  Female       Pune
8    Yash Desai    Male        NaN
9    Neha Joshi  Female     Mumbai
10     Raj Shah    Male   Vadodara
11  Anaya Patel  Female      Surat
12  Kunal Mehta    Male  Bangalore
13   Riya Desai  Female  Ahmedabad
14  Vivan Joshi    Male       Pune
15   Pooja Shah  Female      Surat
16  Manav Patel    Male     Mumbai
17  Kiara Mehta  Female   Vadodara
18  Dhruv Desai    Male      Surat
19  Nisha Joshi  Female  Ahmedabad
20  Arjun Joshi    Male     Mumbai
21   Diya Patel  Female  Ahmedabad
22  Rohan Mehta    Male   Vadodara
23  Kavya Desai  Female      Surat
24  Arjun Joshi    Male     Mumbai

In [225]:
filter_row = df[(df["Age"] > 25) & (df["Salary"] > 15000)]
print(filter_row[["Name","Gender","Department","Job_Role","Age","Salary"]])

           Name  Gender Department           Job_Role   Age    Salary
4   Arjun Joshi    Male      Sales                NaN  27.0   45000.0
6     Dev Patel    Male        NaN   Senior Developer  35.0   95000.0
7    Isha Mehta  Female    Finance  Financial Analyst  28.0   70000.0
8    Yash Desai    Male      Sales    Sales Executive  26.0   42000.0
9    Neha Joshi  Female         IT             Tester  30.0   65000.0
12  Kunal Mehta    Male        NaN    Project Manager  41.0  120000.0
13   Riya Desai  Female      Sales      Sales Manager  29.0   78000.0
14  Vivan Joshi    Male    Finance  Financial Analyst  37.0   90000.0
15   Pooja Shah  Female         IT          Developer  26.0   50000.0
16  Manav Patel    Male         HR          Recruiter  32.0   68000.0
17  Kiara Mehta  Female      Sales    Sales Executive  28.0   48000.0
19  Nisha Joshi  Female    Finance         Accountant  39.0  105000.0
20  Arjun Joshi    Male      Sales                NaN  27.0   45000.0
22  Rohan Mehta    Male    Finance         Accountant  29.0   55000.0
23  Kavya Desai  Female         IT       Data Analyst  31.0   62000.0
24  Arjun Joshi    Male      Sales    Sales Executive  27.0   45000.0

In [226]:
filter_row = df[(df["Age"] > 25) | (df["Salary"] > 25000)]
print(filter_row[["Name","Gender","Department","Job_Role","Salary","Age"]])

           Name  Gender Department           Job_Role    Salary   Age
0    Aarav Shah    Male         IT          Developer   28000.0  23.0
1    Diya Patel  Female         HR       HR Executive   32000.0  25.0
2   Rohan Mehta    Male    Finance         Accountant   55000.0   NaN
3   Kavya Desai  Female         IT       Data Analyst       NaN  31.0
4   Arjun Joshi    Male      Sales                NaN   45000.0  27.0
5     Mira Shah  Female         HR          Recruiter   35000.0  24.0
6     Dev Patel    Male        NaN   Senior Developer   95000.0  35.0
7    Isha Mehta  Female    Finance  Financial Analyst   70000.0  28.0
8    Yash Desai    Male      Sales    Sales Executive   42000.0  26.0
9    Neha Joshi  Female         IT             Tester   65000.0  30.0
10     Raj Shah    Male    Finance         Accountant       NaN  33.0
11  Anaya Patel  Female         HR       HR Executive   30000.0  22.0
12  Kunal Mehta    Male        NaN    Project Manager  120000.0  41.0
13   Riya Desai  Female      Sales      Sales Manager   78000.0  29.0
14  Vivan Joshi    Male    Finance  Financial Analyst   90000.0  37.0
15   Pooja Shah  Female         IT          Developer   50000.0  26.0
16  Manav Patel    Male         HR          Recruiter   68000.0  32.0
17  Kiara Mehta  Female      Sales    Sales Executive   48000.0  28.0
18  Dhruv Desai    Male         IT             Tester   38000.0  24.0
19  Nisha Joshi  Female    Finance         Accountant  105000.0  39.0
20  Arjun Joshi    Male      Sales                NaN   45000.0  27.0
21   Diya Patel  Female         HR       HR Executive   32000.0  25.0
22  Rohan Mehta    Male    Finance         Accountant   55000.0  29.0
23  Kavya Desai  Female         IT       Data Analyst   62000.0  31.0
24  Arjun Joshi    Male      Sales    Sales Executive   45000.0  27.0

In [227]:
df.duplicated().sum()

np.int64(1)

In [228]:
df[df.duplicated()]

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience_Years,Salary,Joining_Year,Performance_Score,City,Education,Remote,Overtime_Hours,Leave_Days
20,1005,Arjun Joshi,27.0,Male,Sales,NaN,4.0,45000.0,2021,7.2,Mumbai,BBA,No,4.0,NaN

In [229]:
df = df.drop_duplicates()
df

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience_Years,Salary,Joining_Year,Performance_Score,City,Education,Remote,Overtime_Hours,Leave_Days
0,1001,Aarav Shah,23.0,Male,IT,Developer,1.0,28000.0,2024,7.5,Surat,BSc IT,Yes,5.0,8.0
1,1002,Diya Patel,25.0,Female,HR,HR Executive,2.0,32000.0,2023,8.1,Ahmedabad,MBA,No,2.0,6.0
2,1003,Rohan Mehta,NaN,Male,Finance,Accountant,5.0,55000.0,2020,6.8,Vadodara,BCom,Yes,8.0,12.0
3,1004,Kavya Desai,31.0,Female,IT,Data Analyst,7.0,NaN,2018,9.0,Surat,BSc IT,Yes,10.0,5.0
4,1005,Arjun Joshi,27.0,Male,Sales,NaN,4.0,45000.0,2021,7.2,Mumbai,BBA,No,4.0,NaN
5,1006,Mira Shah,24.0,Female,HR,Recruiter,2.0,35000.0,2023,NaN,Surat,MBA,Yes,3.0,7.0
6,1007,Dev Patel,35.0,Male,NaN,Senior Developer,10.0,95000.0,2015,9.4,Ahmedabad,MCA,Yes,12.0,4.0
7,1008,Isha Mehta,28.0,Female,Finance,Financial Analyst,NaN,70000.0,2019,7.8,Pune,MCom,No,6.0,9.0
8,1009,Yash Desai,26.0,Male,Sales,Sales Executive,3.0,42000.0,2022,6.9,NaN,BBA,No,7.0,11.0
9,1010,Neha Joshi,30.0,Female,IT,Tester,7.0,65000.0,2018,8.8,Mumbai,BSc IT,NaN,9.0,6.0
10,1011,Raj Shah,33.0,Male,Finance,Accountant,9.0,NaN,2017,7.1,Vadodara,BCom,No,5.0,13.0
11,1012,Anaya Patel,22.0,Female,HR,HR Executive,1.0,30000.0,2025,8.0,Surat,MBA,Yes,1.0,5.0
12,1013,Kunal Mehta,41.0,Male,NaN,Project Manager,15.0,120000.0,2010,9.2,Bangalore,MCA,Yes,15.0,3.0
13,1014,Riya Desai,29.0,Female,Sales,Sales Manager,6.0,78000.0,2019,NaN,Ahmedabad,MBA,No,8.0,8.0
14,1015,Vivan Joshi,37.0,Male,Finance,Financial Analyst,11.0,90000.0,2014,7.9,Pune,MCom,Yes,10.0,7.0
15,1016,Pooja Shah,26.0,Female,IT,Developer,4.0,50000.0,2021,7.4,Surat,BSc IT,Yes,6.0,10.0
16,1017,Manav Patel,32.0,Male,HR,Recruiter,8.0,68000.0,2017,8.7,Mumbai,NaN,No,4.0,6.0
17,1018,Kiara Mehta,28.0,Female,Sales,Sales Executive,5.0,48000.0,2020,6.5,Vadodara,BBA,No,7.0,12.0
18,1019,Dhruv Desai,24.0,Male,IT,Tester,2.0,38000.0,2024,7.0,Surat,BSc IT,Yes,NaN,9.0
19,1020,Nisha Joshi,39.0,Female,Finance,Accountant,13.0,105000.0,2012,9.1,Ahmedabad,BCom,No,11.0,4.0
21,1022,Diya Patel,25.0,Female,HR,HR Executive,2.0,32000.0,2023,8.1,Ahmedabad,MBA,No,2.0,6.0
22,1023,Rohan Mehta,29.0,Male,Finance,Accountant,5.0,55000.0,2020,6.8,Vadodara,BCom,Yes,8.0,12.0
23,1024,Kavya Desai,31.0,Female,IT,Data Analyst,7.0,62000.0,2018,9.0,Surat,BSc IT,Yes,10.0,5.0
24,1025,Arjun Joshi,27.0,Male,Sales,Sales Executive,4.0,45000.0,2021,7.2,Mumbai,BBA,No,4.0,10.0

In [230]:
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
Gender               0
Department           2
Job_Role             1
Experience_Years     1
Salary               2
Joining_Year         0
Performance_Score    2
City                 1
Education            1
Remote               1
Overtime_Hours       1
Leave_Days           1
dtype: int64

In [231]:
df.info()

<class 'pandas.DataFrame'>
Index: 24 entries, 0 to 24
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        24 non-null     int64
 1   Name               24 non-null     str
 2   Age                23 non-null     float64
 3   Gender             24 non-null     str
 4   Department         22 non-null     str
 5   Job_Role           23 non-null     str
 6   Experience_Years   23 non-null     float64
 7   Salary             22 non-null     float64
 8   Joining_Year       24 non-null     int64
 9   Performance_Score  22 non-null     float64
 10  City               23 non-null     str
 11  Education          23 non-null     str
 12  Remote             23 non-null     str
 13  Overtime_Hours     23 non-null     float64
 14  Leave_Days         23 non-null     float64
dtypes: float64(6), int64(2), str(7)
memory usage: 4.0 KB

In [232]:
df["Department"].dtype

In [233]:
df["Department"].isnull().sum()

np.int64(2)

In [234]:
df["Department"].mode()

0    Finance
1         IT
Name: Department, dtype: str

In [235]:
df["Department"].mode()[0]

'Finance'

In [236]:
df["Department"] = df["Department"].fillna(
    df["Department"].mode()[0]
)
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
Gender               0
Department           0
Job_Role             1
Experience_Years     1
Salary               2
Joining_Year         0
Performance_Score    2
City                 1
Education            1
Remote               1
Overtime_Hours       1
Leave_Days           1
dtype: int64

In [237]:
df["Job_Role"] = df["Job_Role"].fillna(
    df["Job_Role"].mode()[0]
)
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
Gender               0
Department           0
Job_Role             0
Experience_Years     1
Salary               2
Joining_Year         0
Performance_Score    2
City                 1
Education            1
Remote               1
Overtime_Hours       1
Leave_Days           1
dtype: int64

In [238]:
df["City"] = df["City"].fillna(
    df["City"].mode()[0]
)
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
Gender               0
Department           0
Job_Role             0
Experience_Years     1
Salary               2
Joining_Year         0
Performance_Score    2
City                 0
Education            1
Remote               1
Overtime_Hours       1
Leave_Days           1
dtype: int64

In [239]:
df["Education"] = df["Education"].fillna(
    df["Education"].mode()[0]
)
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
Gender               0
Department           0
Job_Role             0
Experience_Years     1
Salary               2
Joining_Year         0
Performance_Score    2
City                 0
Education            0
Remote               1
Overtime_Hours       1
Leave_Days           1
dtype: int64

In [240]:
df["Remote"] = df["Remote"].fillna(
    df["Remote"].mode()[0]
)
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
Gender               0
Department           0
Job_Role             0
Experience_Years     1
Salary               2
Joining_Year         0
Performance_Score    2
City                 0
Education            0
Remote               0
Overtime_Hours       1
Leave_Days           1
dtype: int64

In [241]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [242]:
df["Experience_Years"] = df["Experience_Years"].fillna(df["Experience_Years"].mean())

In [243]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [244]:
df["Performance_Score"] = df["Performance_Score"].fillna(df["Performance_Score"].mean())

In [245]:
df["Overtime_Hours"] = df["Overtime_Hours"].fillna(df["Overtime_Hours"].mean())

In [246]:
df["Leave_Days"] = df["Leave_Days"].fillna(df["Leave_Days"].mean())

In [247]:
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  0
Gender               0
Department           0
Job_Role             0
Experience_Years     0
Salary               0
Joining_Year         0
Performance_Score    0
City                 0
Education            0
Remote               0
Overtime_Hours       0
Leave_Days           0
dtype: int64

In [248]:
df

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience_Years,Salary,Joining_Year,Performance_Score,City,Education,Remote,Overtime_Hours,Leave_Days
0,1001,Aarav Shah,23.000000,Male,IT,Developer,1.000000,28000.000000,2024,7.500000,Surat,BSc IT,Yes,5.000000,8.00000
1,1002,Diya Patel,25.000000,Female,HR,HR Executive,2.000000,32000.000000,2023,8.100000,Ahmedabad,MBA,No,2.000000,6.00000
2,1003,Rohan Mehta,29.217391,Male,Finance,Accountant,5.000000,55000.000000,2020,6.800000,Vadodara,BCom,Yes,8.000000,12.00000
3,1004,Kavya Desai,31.000000,Female,IT,Data Analyst,7.000000,58545.454545,2018,9.000000,Surat,BSc IT,Yes,10.000000,5.00000
4,1005,Arjun Joshi,27.000000,Male,Sales,Accountant,4.000000,45000.000000,2021,7.200000,Mumbai,BBA,No,4.000000,7.73913
5,1006,Mira Shah,24.000000,Female,HR,Recruiter,2.000000,35000.000000,2023,7.886364,Surat,MBA,Yes,3.000000,7.00000
6,1007,Dev Patel,35.000000,Male,Finance,Senior Developer,10.000000,95000.000000,2015,9.400000,Ahmedabad,MCA,Yes,12.000000,4.00000
7,1008,Isha Mehta,28.000000,Female,Finance,Financial Analyst,5.782609,70000.000000,2019,7.800000,Pune,MCom,No,6.000000,9.00000
8,1009,Yash Desai,26.000000,Male,Sales,Sales Executive,3.000000,42000.000000,2022,6.900000,Surat,BBA,No,7.000000,11.00000
9,1010,Neha Joshi,30.000000,Female,IT,Tester,7.000000,65000.000000,2018,8.800000,Mumbai,BSc IT,Yes,9.000000,6.00000
10,1011,Raj Shah,33.000000,Male,Finance,Accountant,9.000000,58545.454545,2017,7.100000,Vadodara,BCom,No,5.000000,13.00000
11,1012,Anaya Patel,22.000000,Female,HR,HR Executive,1.000000,30000.000000,2025,8.000000,Surat,MBA,Yes,1.000000,5.00000
12,1013,Kunal Mehta,41.000000,Male,Finance,Project Manager,15.000000,120000.000000,2010,9.200000,Bangalore,MCA,Yes,15.000000,3.00000
13,1014,Riya Desai,29.000000,Female,Sales,Sales Manager,6.000000,78000.000000,2019,7.886364,Ahmedabad,MBA,No,8.000000,8.00000
14,1015,Vivan Joshi,37.000000,Male,Finance,Financial Analyst,11.000000,90000.000000,2014,7.900000,Pune,MCom,Yes,10.000000,7.00000
15,1016,Pooja Shah,26.000000,Female,IT,Developer,4.000000,50000.000000,2021,7.400000,Surat,BSc IT,Yes,6.000000,10.00000
16,1017,Manav Patel,32.000000,Male,HR,Recruiter,8.000000,68000.000000,2017,8.700000,Mumbai,BSc IT,No,4.000000,6.00000
17,1018,Kiara Mehta,28.000000,Female,Sales,Sales Executive,5.000000,48000.000000,2020,6.500000,Vadodara,BBA,No,7.000000,12.00000
18,1019,Dhruv Desai,24.000000,Male,IT,Tester,2.000000,38000.000000,2024,7.000000,Surat,BSc IT,Yes,6.826087,9.00000
19,1020,Nisha Joshi,39.000000,Female,Finance,Accountant,13.000000,105000.000000,2012,9.100000,Ahmedabad,BCom,No,11.000000,4.00000
21,1022,Diya Patel,25.000000,Female,HR,HR Executive,2.000000,32000.000000,2023,8.100000,Ahmedabad,MBA,No,2.000000,6.00000
22,1023,Rohan Mehta,29.000000,Male,Finance,Accountant,5.000000,55000.000000,2020,6.800000,Vadodara,BCom,Yes,8.000000,12.00000
23,1024,Kavya Desai,31.000000,Female,IT,Data Analyst,7.000000,62000.000000,2018,9.000000,Surat,BSc IT,Yes,10.000000,5.00000
24,1025,Arjun Joshi,27.000000,Male,Sales,Sales Executive,4.000000,45000.000000,2021,7.200000,Mumbai,BBA,No,4.000000,10.00000

In [249]:
df = pd.get_dummies(df, columns=["Department" , "City" , "Education" , "Remote" , "Job_Role"],dtype=int )

In [250]:
df

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
0,1001,Aarav Shah,23.000000,Male,1.000000,28000.000000,2024,7.500000,5.000000,8.00000,...,0,1,0,0,0,0,0,0,0,0
1,1002,Diya Patel,25.000000,Female,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,29.217391,Male,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
3,1004,Kavya Desai,31.000000,Female,7.000000,58545.454545,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
4,1005,Arjun Joshi,27.000000,Male,4.000000,45000.000000,2021,7.200000,4.000000,7.73913,...,0,0,0,0,0,0,0,0,0,0
5,1006,Mira Shah,24.000000,Female,2.000000,35000.000000,2023,7.886364,3.000000,7.00000,...,0,0,0,0,0,1,0,0,0,0
6,1007,Dev Patel,35.000000,Male,10.000000,95000.000000,2015,9.400000,12.000000,4.00000,...,0,0,0,0,0,0,0,0,1,0
7,1008,Isha Mehta,28.000000,Female,5.782609,70000.000000,2019,7.800000,6.000000,9.00000,...,0,0,1,0,0,0,0,0,0,0
8,1009,Yash Desai,26.000000,Male,3.000000,42000.000000,2022,6.900000,7.000000,11.00000,...,0,0,0,0,0,0,1,0,0,0
9,1010,Neha Joshi,30.000000,Female,7.000000,65000.000000,2018,8.800000,9.000000,6.00000,...,0,0,0,0,0,0,0,0,0,1
10,1011,Raj Shah,33.000000,Male,9.000000,58545.454545,2017,7.100000,5.000000,13.00000,...,0,0,0,0,0,0,0,0,0,0
11,1012,Anaya Patel,22.000000,Female,1.000000,30000.000000,2025,8.000000,1.000000,5.00000,...,0,0,0,1,0,0,0,0,0,0
12,1013,Kunal Mehta,41.000000,Male,15.000000,120000.000000,2010,9.200000,15.000000,3.00000,...,0,0,0,0,1,0,0,0,0,0
13,1014,Riya Desai,29.000000,Female,6.000000,78000.000000,2019,7.886364,8.000000,8.00000,...,0,0,0,0,0,0,0,1,0,0
14,1015,Vivan Joshi,37.000000,Male,11.000000,90000.000000,2014,7.900000,10.000000,7.00000,...,0,0,1,0,0,0,0,0,0,0
15,1016,Pooja Shah,26.000000,Female,4.000000,50000.000000,2021,7.400000,6.000000,10.00000,...,0,1,0,0,0,0,0,0,0,0
16,1017,Manav Patel,32.000000,Male,8.000000,68000.000000,2017,8.700000,4.000000,6.00000,...,0,0,0,0,0,1,0,0,0,0
17,1018,Kiara Mehta,28.000000,Female,5.000000,48000.000000,2020,6.500000,7.000000,12.00000,...,0,0,0,0,0,0,1,0,0,0
18,1019,Dhruv Desai,24.000000,Male,2.000000,38000.000000,2024,7.000000,6.826087,9.00000,...,0,0,0,0,0,0,0,0,0,1
19,1020,Nisha Joshi,39.000000,Female,13.000000,105000.000000,2012,9.100000,11.000000,4.00000,...,0,0,0,0,0,0,0,0,0,0
21,1022,Diya Patel,25.000000,Female,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
22,1023,Rohan Mehta,29.000000,Male,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
23,1024,Kavya Desai,31.000000,Female,7.000000,62000.000000,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
24,1025,Arjun Joshi,27.000000,Male,4.000000,45000.000000,2021,7.200000,4.000000,10.00000,...,0,0,0,0,0,0,1,0,0,0

In [251]:
df["Gender"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})
df

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
0,1001,Aarav Shah,23.000000,1,1.000000,28000.000000,2024,7.500000,5.000000,8.00000,...,0,1,0,0,0,0,0,0,0,0
1,1002,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,29.217391,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
3,1004,Kavya Desai,31.000000,0,7.000000,58545.454545,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
4,1005,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,7.73913,...,0,0,0,0,0,0,0,0,0,0
5,1006,Mira Shah,24.000000,0,2.000000,35000.000000,2023,7.886364,3.000000,7.00000,...,0,0,0,0,0,1,0,0,0,0
6,1007,Dev Patel,35.000000,1,10.000000,95000.000000,2015,9.400000,12.000000,4.00000,...,0,0,0,0,0,0,0,0,1,0
7,1008,Isha Mehta,28.000000,0,5.782609,70000.000000,2019,7.800000,6.000000,9.00000,...,0,0,1,0,0,0,0,0,0,0
8,1009,Yash Desai,26.000000,1,3.000000,42000.000000,2022,6.900000,7.000000,11.00000,...,0,0,0,0,0,0,1,0,0,0
9,1010,Neha Joshi,30.000000,0,7.000000,65000.000000,2018,8.800000,9.000000,6.00000,...,0,0,0,0,0,0,0,0,0,1
10,1011,Raj Shah,33.000000,1,9.000000,58545.454545,2017,7.100000,5.000000,13.00000,...,0,0,0,0,0,0,0,0,0,0
11,1012,Anaya Patel,22.000000,0,1.000000,30000.000000,2025,8.000000,1.000000,5.00000,...,0,0,0,1,0,0,0,0,0,0
12,1013,Kunal Mehta,41.000000,1,15.000000,120000.000000,2010,9.200000,15.000000,3.00000,...,0,0,0,0,1,0,0,0,0,0
13,1014,Riya Desai,29.000000,0,6.000000,78000.000000,2019,7.886364,8.000000,8.00000,...,0,0,0,0,0,0,0,1,0,0
14,1015,Vivan Joshi,37.000000,1,11.000000,90000.000000,2014,7.900000,10.000000,7.00000,...,0,0,1,0,0,0,0,0,0,0
15,1016,Pooja Shah,26.000000,0,4.000000,50000.000000,2021,7.400000,6.000000,10.00000,...,0,1,0,0,0,0,0,0,0,0
16,1017,Manav Patel,32.000000,1,8.000000,68000.000000,2017,8.700000,4.000000,6.00000,...,0,0,0,0,0,1,0,0,0,0
17,1018,Kiara Mehta,28.000000,0,5.000000,48000.000000,2020,6.500000,7.000000,12.00000,...,0,0,0,0,0,0,1,0,0,0
18,1019,Dhruv Desai,24.000000,1,2.000000,38000.000000,2024,7.000000,6.826087,9.00000,...,0,0,0,0,0,0,0,0,0,1
19,1020,Nisha Joshi,39.000000,0,13.000000,105000.000000,2012,9.100000,11.000000,4.00000,...,0,0,0,0,0,0,0,0,0,0
21,1022,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
22,1023,Rohan Mehta,29.000000,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
23,1024,Kavya Desai,31.000000,0,7.000000,62000.000000,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
24,1025,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,10.00000,...,0,0,0,0,0,0,1,0,0,0

In [256]:
df = df.dropna()

In [257]:
df.to_csv("Cleaned_dataset.csv",index=False)

In [ ]:
df.describe

,Employee_ID,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,Department_Finance,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,...,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,1012.666667,29.217391,0.500000,5.782609,58545.454545,2019.333333,7.886364,6.826087,7.739130,0.333333,...,0.083333,0.083333,0.083333,0.125000,0.041667,0.083333,0.125000,0.041667,0.041667,0.083333
std,7.322786,4.986560,0.510754,3.752756,24574.159763,3.829708,0.873919,3.472277,2.892530,0.481543,...,0.282330,0.282330,0.282330,0.337832,0.204124,0.282330,0.337832,0.204124,0.204124,0.282330
min,1001.000000,22.000000,0.000000,1.000000,28000.000000,2010.000000,6.500000,1.000000,3.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1006.750000,25.750000,0.000000,2.750000,41000.000000,2017.750000,7.175000,4.000000,5.750000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1012.500000,28.500000,0.500000,5.000000,55000.000000,2020.000000,7.886364,6.913043,7.369565,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1018.250000,31.250000,1.000000,7.250000,68500.000000,2022.250000,8.725000,9.250000,10.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1025.000000,41.000000,1.000000,15.000000,120000.000000,2025.000000,9.400000,15.000000,13.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

IQR = Q3 - Q1

Lower Bound = Q1 - (1.5 × IQR)

Upper Bound = Q3 + (1.5 × IQR)

---

Q1 → 25th percentile
Q2 → 50th percentile (Median)
Q3 → 75th percentile

In [260]:
q1 = 41000.000000
q3 = 68500.000000

IQR = q3 - q1

Imin = q1 - (1.5 * IQR)
Imax = q3 + (1.5 * IQR)
df[(df["Salary"] < Imin) | (df["Salary"] > Imax)]

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
12,1013,Kunal Mehta,41.0,1,15.0,120000.0,2010,9.2,15.0,3.0,...,0,0,0,0,1,0,0,0,0,0

In [262]:
df = df[(df["Salary"] >= Imin) & (df["Salary"] <= Imax)]
df

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
0,1001,Aarav Shah,23.000000,1,1.000000,28000.000000,2024,7.500000,5.000000,8.00000,...,0,1,0,0,0,0,0,0,0,0
1,1002,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,29.217391,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
3,1004,Kavya Desai,31.000000,0,7.000000,58545.454545,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
4,1005,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,7.73913,...,0,0,0,0,0,0,0,0,0,0
5,1006,Mira Shah,24.000000,0,2.000000,35000.000000,2023,7.886364,3.000000,7.00000,...,0,0,0,0,0,1,0,0,0,0
6,1007,Dev Patel,35.000000,1,10.000000,95000.000000,2015,9.400000,12.000000,4.00000,...,0,0,0,0,0,0,0,0,1,0
7,1008,Isha Mehta,28.000000,0,5.782609,70000.000000,2019,7.800000,6.000000,9.00000,...,0,0,1,0,0,0,0,0,0,0
8,1009,Yash Desai,26.000000,1,3.000000,42000.000000,2022,6.900000,7.000000,11.00000,...,0,0,0,0,0,0,1,0,0,0
9,1010,Neha Joshi,30.000000,0,7.000000,65000.000000,2018,8.800000,9.000000,6.00000,...,0,0,0,0,0,0,0,0,0,1
10,1011,Raj Shah,33.000000,1,9.000000,58545.454545,2017,7.100000,5.000000,13.00000,...,0,0,0,0,0,0,0,0,0,0
11,1012,Anaya Patel,22.000000,0,1.000000,30000.000000,2025,8.000000,1.000000,5.00000,...,0,0,0,1,0,0,0,0,0,0
13,1014,Riya Desai,29.000000,0,6.000000,78000.000000,2019,7.886364,8.000000,8.00000,...,0,0,0,0,0,0,0,1,0,0
14,1015,Vivan Joshi,37.000000,1,11.000000,90000.000000,2014,7.900000,10.000000,7.00000,...,0,0,1,0,0,0,0,0,0,0
15,1016,Pooja Shah,26.000000,0,4.000000,50000.000000,2021,7.400000,6.000000,10.00000,...,0,1,0,0,0,0,0,0,0,0
16,1017,Manav Patel,32.000000,1,8.000000,68000.000000,2017,8.700000,4.000000,6.00000,...,0,0,0,0,0,1,0,0,0,0
17,1018,Kiara Mehta,28.000000,0,5.000000,48000.000000,2020,6.500000,7.000000,12.00000,...,0,0,0,0,0,0,1,0,0,0
18,1019,Dhruv Desai,24.000000,1,2.000000,38000.000000,2024,7.000000,6.826087,9.00000,...,0,0,0,0,0,0,0,0,0,1
19,1020,Nisha Joshi,39.000000,0,13.000000,105000.000000,2012,9.100000,11.000000,4.00000,...,0,0,0,0,0,0,0,0,0,0
21,1022,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
22,1023,Rohan Mehta,29.000000,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
23,1024,Kavya Desai,31.000000,0,7.000000,62000.000000,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
24,1025,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,10.00000,...,0,0,0,0,0,0,1,0,0,0

# Z Score

### Min = Mean() - 3*std()
### Max = Mean() + 3*std()

Min = df["Salary"].mean() - 3 * df["Salary"].std()
Max = df["Salary"].mean() + 3 * df["Salary"].std()

---
df[(df["Salary"] < Min) | (df["Salary"] > Max)]

df = df[(df["Salary]>=Min) & (df["Salary]<=Max)]
df

# Date & Time Formatting

df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)

### output
"19/08/2026" → 2026-08-19
"2026-08-20" → 2026-08-20
"abc"        → NaT

---

df["Joining_Date"].dtype

df["Day_Name"] = df["Joining_Date"].dt.day_name()
df["Day"] = df["Joining_Date"].dt.day
df["Month"] = df["Joining_Date"].dt.month
df["Year"] = df["Joining_Date"].dt.year

---

df.sort_values("Joining_Date", ascending=False)
df.sort_values("Joining_Date")

df["Days"] = (
    df["End_Date"] - df["Joining_Date"]
).dt.days
Example: calculate days between two dates:

In [ ]:
df["Name"] = df["Name"].str.strip()

In [268]:
df["Name"] = df["Name"].str.lower()
df

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
0,1001,aarav shah,23.000000,1,1.000000,28000.000000,2024,7.500000,5.000000,8.00000,...,0,1,0,0,0,0,0,0,0,0
1,1002,diya patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
2,1003,rohan mehta,29.217391,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
3,1004,kavya desai,31.000000,0,7.000000,58545.454545,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
4,1005,arjun joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,7.73913,...,0,0,0,0,0,0,0,0,0,0
5,1006,mira shah,24.000000,0,2.000000,35000.000000,2023,7.886364,3.000000,7.00000,...,0,0,0,0,0,1,0,0,0,0
6,1007,dev patel,35.000000,1,10.000000,95000.000000,2015,9.400000,12.000000,4.00000,...,0,0,0,0,0,0,0,0,1,0
7,1008,isha mehta,28.000000,0,5.782609,70000.000000,2019,7.800000,6.000000,9.00000,...,0,0,1,0,0,0,0,0,0,0
8,1009,yash desai,26.000000,1,3.000000,42000.000000,2022,6.900000,7.000000,11.00000,...,0,0,0,0,0,0,1,0,0,0
9,1010,neha joshi,30.000000,0,7.000000,65000.000000,2018,8.800000,9.000000,6.00000,...,0,0,0,0,0,0,0,0,0,1
10,1011,raj shah,33.000000,1,9.000000,58545.454545,2017,7.100000,5.000000,13.00000,...,0,0,0,0,0,0,0,0,0,0
11,1012,anaya patel,22.000000,0,1.000000,30000.000000,2025,8.000000,1.000000,5.00000,...,0,0,0,1,0,0,0,0,0,0
13,1014,riya desai,29.000000,0,6.000000,78000.000000,2019,7.886364,8.000000,8.00000,...,0,0,0,0,0,0,0,1,0,0
14,1015,vivan joshi,37.000000,1,11.000000,90000.000000,2014,7.900000,10.000000,7.00000,...,0,0,1,0,0,0,0,0,0,0
15,1016,pooja shah,26.000000,0,4.000000,50000.000000,2021,7.400000,6.000000,10.00000,...,0,1,0,0,0,0,0,0,0,0
16,1017,manav patel,32.000000,1,8.000000,68000.000000,2017,8.700000,4.000000,6.00000,...,0,0,0,0,0,1,0,0,0,0
17,1018,kiara mehta,28.000000,0,5.000000,48000.000000,2020,6.500000,7.000000,12.00000,...,0,0,0,0,0,0,1,0,0,0
18,1019,dhruv desai,24.000000,1,2.000000,38000.000000,2024,7.000000,6.826087,9.00000,...,0,0,0,0,0,0,0,0,0,1
19,1020,nisha joshi,39.000000,0,13.000000,105000.000000,2012,9.100000,11.000000,4.00000,...,0,0,0,0,0,0,0,0,0,0
21,1022,diya patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
22,1023,rohan mehta,29.000000,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
23,1024,kavya desai,31.000000,0,7.000000,62000.000000,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
24,1025,arjun joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,10.00000,...,0,0,0,0,0,0,1,0,0,0

In [269]:
df["Name"] = df["Name"].str.upper()
df

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
0,1001,AARAV SHAH,23.000000,1,1.000000,28000.000000,2024,7.500000,5.000000,8.00000,...,0,1,0,0,0,0,0,0,0,0
1,1002,DIYA PATEL,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
2,1003,ROHAN MEHTA,29.217391,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
3,1004,KAVYA DESAI,31.000000,0,7.000000,58545.454545,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
4,1005,ARJUN JOSHI,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,7.73913,...,0,0,0,0,0,0,0,0,0,0
5,1006,MIRA SHAH,24.000000,0,2.000000,35000.000000,2023,7.886364,3.000000,7.00000,...,0,0,0,0,0,1,0,0,0,0
6,1007,DEV PATEL,35.000000,1,10.000000,95000.000000,2015,9.400000,12.000000,4.00000,...,0,0,0,0,0,0,0,0,1,0
7,1008,ISHA MEHTA,28.000000,0,5.782609,70000.000000,2019,7.800000,6.000000,9.00000,...,0,0,1,0,0,0,0,0,0,0
8,1009,YASH DESAI,26.000000,1,3.000000,42000.000000,2022,6.900000,7.000000,11.00000,...,0,0,0,0,0,0,1,0,0,0
9,1010,NEHA JOSHI,30.000000,0,7.000000,65000.000000,2018,8.800000,9.000000,6.00000,...,0,0,0,0,0,0,0,0,0,1
10,1011,RAJ SHAH,33.000000,1,9.000000,58545.454545,2017,7.100000,5.000000,13.00000,...,0,0,0,0,0,0,0,0,0,0
11,1012,ANAYA PATEL,22.000000,0,1.000000,30000.000000,2025,8.000000,1.000000,5.00000,...,0,0,0,1,0,0,0,0,0,0
13,1014,RIYA DESAI,29.000000,0,6.000000,78000.000000,2019,7.886364,8.000000,8.00000,...,0,0,0,0,0,0,0,1,0,0
14,1015,VIVAN JOSHI,37.000000,1,11.000000,90000.000000,2014,7.900000,10.000000,7.00000,...,0,0,1,0,0,0,0,0,0,0
15,1016,POOJA SHAH,26.000000,0,4.000000,50000.000000,2021,7.400000,6.000000,10.00000,...,0,1,0,0,0,0,0,0,0,0
16,1017,MANAV PATEL,32.000000,1,8.000000,68000.000000,2017,8.700000,4.000000,6.00000,...,0,0,0,0,0,1,0,0,0,0
17,1018,KIARA MEHTA,28.000000,0,5.000000,48000.000000,2020,6.500000,7.000000,12.00000,...,0,0,0,0,0,0,1,0,0,0
18,1019,DHRUV DESAI,24.000000,1,2.000000,38000.000000,2024,7.000000,6.826087,9.00000,...,0,0,0,0,0,0,0,0,0,1
19,1020,NISHA JOSHI,39.000000,0,13.000000,105000.000000,2012,9.100000,11.000000,4.00000,...,0,0,0,0,0,0,0,0,0,0
21,1022,DIYA PATEL,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
22,1023,ROHAN MEHTA,29.000000,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
23,1024,KAVYA DESAI,31.000000,0,7.000000,62000.000000,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
24,1025,ARJUN JOSHI,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,10.00000,...,0,0,0,0,0,0,1,0,0,0

In [270]:
df["Name"] = df["Name"].str.title()
df

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
0,1001,Aarav Shah,23.000000,1,1.000000,28000.000000,2024,7.500000,5.000000,8.00000,...,0,1,0,0,0,0,0,0,0,0
1,1002,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,29.217391,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
3,1004,Kavya Desai,31.000000,0,7.000000,58545.454545,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
4,1005,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,7.73913,...,0,0,0,0,0,0,0,0,0,0
5,1006,Mira Shah,24.000000,0,2.000000,35000.000000,2023,7.886364,3.000000,7.00000,...,0,0,0,0,0,1,0,0,0,0
6,1007,Dev Patel,35.000000,1,10.000000,95000.000000,2015,9.400000,12.000000,4.00000,...,0,0,0,0,0,0,0,0,1,0
7,1008,Isha Mehta,28.000000,0,5.782609,70000.000000,2019,7.800000,6.000000,9.00000,...,0,0,1,0,0,0,0,0,0,0
8,1009,Yash Desai,26.000000,1,3.000000,42000.000000,2022,6.900000,7.000000,11.00000,...,0,0,0,0,0,0,1,0,0,0
9,1010,Neha Joshi,30.000000,0,7.000000,65000.000000,2018,8.800000,9.000000,6.00000,...,0,0,0,0,0,0,0,0,0,1
10,1011,Raj Shah,33.000000,1,9.000000,58545.454545,2017,7.100000,5.000000,13.00000,...,0,0,0,0,0,0,0,0,0,0
11,1012,Anaya Patel,22.000000,0,1.000000,30000.000000,2025,8.000000,1.000000,5.00000,...,0,0,0,1,0,0,0,0,0,0
13,1014,Riya Desai,29.000000,0,6.000000,78000.000000,2019,7.886364,8.000000,8.00000,...,0,0,0,0,0,0,0,1,0,0
14,1015,Vivan Joshi,37.000000,1,11.000000,90000.000000,2014,7.900000,10.000000,7.00000,...,0,0,1,0,0,0,0,0,0,0
15,1016,Pooja Shah,26.000000,0,4.000000,50000.000000,2021,7.400000,6.000000,10.00000,...,0,1,0,0,0,0,0,0,0,0
16,1017,Manav Patel,32.000000,1,8.000000,68000.000000,2017,8.700000,4.000000,6.00000,...,0,0,0,0,0,1,0,0,0,0
17,1018,Kiara Mehta,28.000000,0,5.000000,48000.000000,2020,6.500000,7.000000,12.00000,...,0,0,0,0,0,0,1,0,0,0
18,1019,Dhruv Desai,24.000000,1,2.000000,38000.000000,2024,7.000000,6.826087,9.00000,...,0,0,0,0,0,0,0,0,0,1
19,1020,Nisha Joshi,39.000000,0,13.000000,105000.000000,2012,9.100000,11.000000,4.00000,...,0,0,0,0,0,0,0,0,0,0
21,1022,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
22,1023,Rohan Mehta,29.000000,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
23,1024,Kavya Desai,31.000000,0,7.000000,62000.000000,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
24,1025,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,10.00000,...,0,0,0,0,0,0,1,0,0,0

df["Department"] = df["Department"].str.upper()

df["Department"] = df["Department"].replace({
    "I.T.": "IT"
})

Name       → Title Case
Email      → Lowercase
Department → Consistent format
City       → Title Case

In [271]:
df["Name"].unique()
df

,Employee_ID,Name,Age,Gender,Experience_Years,Salary,Joining_Year,Performance_Score,Overtime_Hours,Leave_Days,...,Job_Role_Data Analyst,Job_Role_Developer,Job_Role_Financial Analyst,Job_Role_HR Executive,Job_Role_Project Manager,Job_Role_Recruiter,Job_Role_Sales Executive,Job_Role_Sales Manager,Job_Role_Senior Developer,Job_Role_Tester
0,1001,Aarav Shah,23.000000,1,1.000000,28000.000000,2024,7.500000,5.000000,8.00000,...,0,1,0,0,0,0,0,0,0,0
1,1002,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
2,1003,Rohan Mehta,29.217391,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
3,1004,Kavya Desai,31.000000,0,7.000000,58545.454545,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
4,1005,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,7.73913,...,0,0,0,0,0,0,0,0,0,0
5,1006,Mira Shah,24.000000,0,2.000000,35000.000000,2023,7.886364,3.000000,7.00000,...,0,0,0,0,0,1,0,0,0,0
6,1007,Dev Patel,35.000000,1,10.000000,95000.000000,2015,9.400000,12.000000,4.00000,...,0,0,0,0,0,0,0,0,1,0
7,1008,Isha Mehta,28.000000,0,5.782609,70000.000000,2019,7.800000,6.000000,9.00000,...,0,0,1,0,0,0,0,0,0,0
8,1009,Yash Desai,26.000000,1,3.000000,42000.000000,2022,6.900000,7.000000,11.00000,...,0,0,0,0,0,0,1,0,0,0
9,1010,Neha Joshi,30.000000,0,7.000000,65000.000000,2018,8.800000,9.000000,6.00000,...,0,0,0,0,0,0,0,0,0,1
10,1011,Raj Shah,33.000000,1,9.000000,58545.454545,2017,7.100000,5.000000,13.00000,...,0,0,0,0,0,0,0,0,0,0
11,1012,Anaya Patel,22.000000,0,1.000000,30000.000000,2025,8.000000,1.000000,5.00000,...,0,0,0,1,0,0,0,0,0,0
13,1014,Riya Desai,29.000000,0,6.000000,78000.000000,2019,7.886364,8.000000,8.00000,...,0,0,0,0,0,0,0,1,0,0
14,1015,Vivan Joshi,37.000000,1,11.000000,90000.000000,2014,7.900000,10.000000,7.00000,...,0,0,1,0,0,0,0,0,0,0
15,1016,Pooja Shah,26.000000,0,4.000000,50000.000000,2021,7.400000,6.000000,10.00000,...,0,1,0,0,0,0,0,0,0,0
16,1017,Manav Patel,32.000000,1,8.000000,68000.000000,2017,8.700000,4.000000,6.00000,...,0,0,0,0,0,1,0,0,0,0
17,1018,Kiara Mehta,28.000000,0,5.000000,48000.000000,2020,6.500000,7.000000,12.00000,...,0,0,0,0,0,0,1,0,0,0
18,1019,Dhruv Desai,24.000000,1,2.000000,38000.000000,2024,7.000000,6.826087,9.00000,...,0,0,0,0,0,0,0,0,0,1
19,1020,Nisha Joshi,39.000000,0,13.000000,105000.000000,2012,9.100000,11.000000,4.00000,...,0,0,0,0,0,0,0,0,0,0
21,1022,Diya Patel,25.000000,0,2.000000,32000.000000,2023,8.100000,2.000000,6.00000,...,0,0,0,1,0,0,0,0,0,0
22,1023,Rohan Mehta,29.000000,1,5.000000,55000.000000,2020,6.800000,8.000000,12.00000,...,0,0,0,0,0,0,0,0,0,0
23,1024,Kavya Desai,31.000000,0,7.000000,62000.000000,2018,9.000000,10.000000,5.00000,...,1,0,0,0,0,0,0,0,0,0
24,1025,Arjun Joshi,27.000000,1,4.000000,45000.000000,2021,7.200000,4.000000,10.00000,...,0,0,0,0,0,0,1,0,0,0

In [273]:
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

Total rows: 23
Total columns: 39

In [274]:

print("\nNull values:")
print(df.isnull().sum())

Null values:
Employee_ID                   0
Name                          0
Age                           0
Gender                        0
Experience_Years              0
Salary                        0
Joining_Year                  0
Performance_Score             0
Overtime_Hours                0
Leave_Days                    0
Department_Finance            0
Department_HR                 0
Department_IT                 0
Department_Sales              0
City_Ahmedabad                0
City_Bangalore                0
City_Mumbai                   0
City_Pune                     0
City_Surat                    0
City_Vadodara                 0
Education_BBA                 0
Education_BCom                0
Education_BSc IT              0
Education_MBA                 0
Education_MCA                 0
Education_MCom                0
Remote_No                     0
Remote_Yes                    0
Job_Role_Accountant           0
Job_Role_Data Analyst         0
Job_Role_Developer            0
Job_Role_Financial Analyst    0
Job_Role_HR Executive         0
Job_Role_Project Manager      0
Job_Role_Recruiter            0
Job_Role_Sales Executive      0
Job_Role_Sales Manager        0
Job_Role_Senior Developer     0
Job_Role_Tester               0
dtype: int64

In [275]:
print("\nDuplicate rows:")
print(df.duplicated().sum())

Duplicate rows:
0